// Code generated by herdr-apigen. DO NOT EDIT.

package herdr

// SchemaProtocol is the protocol version of the API schema this code was
// generated from. Compare it with the protocol reported by Ping to detect
// a server that is newer than the generated code.
const SchemaProtocol uint32 = 22
