// Code generated by herdr-apigen. DO NOT EDIT.

package herdr

import "context"

// Method names of the Herdr API.
const (
	MethodAgentExplain               = "agent.explain"
	MethodAgentFocus                 = "agent.focus"
	MethodAgentGet                   = "agent.get"
	MethodAgentList                  = "agent.list"
	MethodAgentPrompt                = "agent.prompt"
	MethodAgentRead                  = "agent.read"
	MethodAgentRename                = "agent.rename"
	MethodAgentSendKeys              = "agent.send_keys"
	MethodAgentStart                 = "agent.start"
	MethodAgentViewClear             = "agent.view.clear"
	MethodAgentViewSet               = "agent.view.set"
	MethodAgentWait                  = "agent.wait"
	MethodClientShellSurfaceSet      = "client_shell.surface.set"
	MethodClientWindowTitleClear     = "client.window_title.clear"
	MethodClientWindowTitleSet       = "client.window_title.set"
	MethodCommandInvoke              = "command.invoke"
	MethodEventsSubscribe            = "events.subscribe"
	MethodEventsWait                 = "events.wait"
	MethodIntegrationInstall         = "integration.install"
	MethodIntegrationList            = "integration.list"
	MethodIntegrationUninstall       = "integration.uninstall"
	MethodLayoutApply                = "layout.apply"
	MethodLayoutExport               = "layout.export"
	MethodLayoutSetSplitRatio        = "layout.set_split_ratio"
	MethodNotificationShow           = "notification.show"
	MethodPaneClearAgentAuthority    = "pane.clear_agent_authority"
	MethodPaneClose                  = "pane.close"
	MethodPaneCopyMotion             = "pane.copy_motion"
	MethodPaneCopySearch             = "pane.copy_search"
	MethodPaneCurrent                = "pane.current"
	MethodPaneEdges                  = "pane.edges"
	MethodPaneEditScrollback         = "pane.edit_scrollback"
	MethodPaneFocus                  = "pane.focus"
	MethodPaneFocusDirection         = "pane.focus_direction"
	MethodPaneGet                    = "pane.get"
	MethodPaneGraphicsClear          = "pane.graphics.clear"
	MethodPaneGraphicsInfo           = "pane.graphics.info"
	MethodPaneGraphicsSet            = "pane.graphics.set"
	MethodPaneInputSet               = "pane.input.set"
	MethodPaneLayout                 = "pane.layout"
	MethodPaneLinkActivate           = "pane.link.activate"
	MethodPaneList                   = "pane.list"
	MethodPaneMove                   = "pane.move"
	MethodPaneNeighbor               = "pane.neighbor"
	MethodPaneProcessInfo            = "pane.process_info"
	MethodPaneRead                   = "pane.read"
	MethodPaneReleaseAgent           = "pane.release_agent"
	MethodPaneRename                 = "pane.rename"
	MethodPaneReportAgent            = "pane.report_agent"
	MethodPaneReportAgentSession     = "pane.report_agent_session"
	MethodPaneReportMetadata         = "pane.report_metadata"
	MethodPaneResize                 = "pane.resize"
	MethodPaneScroll                 = "pane.scroll"
	MethodPaneSelectionRead          = "pane.selection.read"
	MethodPaneSendInput              = "pane.send_input"
	MethodPaneSendKeys               = "pane.send_keys"
	MethodPaneSendText               = "pane.send_text"
	MethodPaneSplit                  = "pane.split"
	MethodPaneSwap                   = "pane.swap"
	MethodPaneWaitForOutput          = "pane.wait_for_output"
	MethodPaneZoom                   = "pane.zoom"
	MethodPing                       = "ping"
	MethodPluginActionInvoke         = "plugin.action.invoke"
	MethodPluginActionList           = "plugin.action.list"
	MethodPluginDisable              = "plugin.disable"
	MethodPluginEnable               = "plugin.enable"
	MethodPluginLink                 = "plugin.link"
	MethodPluginList                 = "plugin.list"
	MethodPluginLogList              = "plugin.log.list"
	MethodPluginPaneClose            = "plugin.pane.close"
	MethodPluginPaneFocus            = "plugin.pane.focus"
	MethodPluginPaneOpen             = "plugin.pane.open"
	MethodPluginUnlink               = "plugin.unlink"
	MethodPopupClose                 = "popup.close"
	MethodProductAnnouncementDismiss = "product_announcement.dismiss"
	MethodReleaseNotesDismiss        = "release_notes.dismiss"
	MethodServerAgentManifests       = "server.agent_manifests"
	MethodServerLiveHandoff          = "server.live_handoff"
	MethodServerReloadAgentManifests = "server.reload_agent_manifests"
	MethodServerReloadConfig         = "server.reload_config"
	MethodServerStop                 = "server.stop"
	MethodSessionSnapshot            = "session.snapshot"
	MethodTabClose                   = "tab.close"
	MethodTabCreate                  = "tab.create"
	MethodTabFocus                   = "tab.focus"
	MethodTabGet                     = "tab.get"
	MethodTabList                    = "tab.list"
	MethodTabMove                    = "tab.move"
	MethodTabRename                  = "tab.rename"
	MethodWorkspaceClose             = "workspace.close"
	MethodWorkspaceCreate            = "workspace.create"
	MethodWorkspaceFocus             = "workspace.focus"
	MethodWorkspaceGet               = "workspace.get"
	MethodWorkspaceList              = "workspace.list"
	MethodWorkspaceMove              = "workspace.move"
	MethodWorkspaceMoveBlock         = "workspace.move_block"
	MethodWorkspaceRename            = "workspace.rename"
	MethodWorkspaceReportMetadata    = "workspace.report_metadata"
	MethodWorktreeCreate             = "worktree.create"
	MethodWorktreeList               = "worktree.list"
	MethodWorktreeOpen               = "worktree.open"
	MethodWorktreeRemove             = "worktree.remove"
)

// AgentExplain calls "agent.explain".
func (c *Client) AgentExplain(ctx context.Context, params AgentTarget) (*AgentExplainResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentExplain, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentExplainResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentExplain, Want: "agent_explain", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentFocus calls "agent.focus".
func (c *Client) AgentFocus(ctx context.Context, params AgentTarget) (*AgentInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentFocus, Want: "agent_info", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentGet calls "agent.get".
func (c *Client) AgentGet(ctx context.Context, params AgentTarget) (*AgentInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentGet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentGet, Want: "agent_info", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentList calls "agent.list".
func (c *Client) AgentList(ctx context.Context) (*AgentListResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentList, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentList, Want: "agent_list", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentPrompt calls "agent.prompt".
func (c *Client) AgentPrompt(ctx context.Context, params AgentPromptParams) (*AgentPromptedResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentPrompt, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentPromptedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentPrompt, Want: "agent_prompted", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentRead calls "agent.read".
func (c *Client) AgentRead(ctx context.Context, params AgentReadParams) (*PaneReadResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentRead, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneReadResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentRead, Want: "pane_read", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentRename calls "agent.rename".
func (c *Client) AgentRename(ctx context.Context, params AgentRenameParams) (*AgentInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentRename, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentRename, Want: "agent_info", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentSendKeys calls "agent.send_keys".
func (c *Client) AgentSendKeys(ctx context.Context, params AgentSendKeysParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentSendKeys, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentSendKeys, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentStart calls "agent.start".
func (c *Client) AgentStart(ctx context.Context, params AgentStartParams) (*AgentStartedResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentStart, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentStartedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentStart, Want: "agent_started", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentViewClear calls "agent.view.clear".
func (c *Client) AgentViewClear(ctx context.Context, params AgentViewClearParams) (*AgentViewResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentViewClear, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentViewResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentViewClear, Want: "agent_view", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentViewSet calls "agent.view.set".
func (c *Client) AgentViewSet(ctx context.Context, params AgentViewSetParams) (*AgentViewResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentViewSet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentViewResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentViewSet, Want: "agent_view", Got: result.ResultType()}
	}
	return typed, nil
}

// AgentWait calls "agent.wait".
func (c *Client) AgentWait(ctx context.Context, params AgentWaitParams) (*AgentInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodAgentWait, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodAgentWait, Want: "agent_info", Got: result.ResultType()}
	}
	return typed, nil
}

// ClientShellSurfaceSet calls "client_shell.surface.set".
func (c *Client) ClientShellSurfaceSet(ctx context.Context, params ClientShellSurfaceSetParams) (*ClientShellSurfaceSetResult, error) {
	raw, err := c.CallRaw(ctx, MethodClientShellSurfaceSet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ClientShellSurfaceSetResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodClientShellSurfaceSet, Want: "client_shell_surface_set", Got: result.ResultType()}
	}
	return typed, nil
}

// ClientWindowTitleClear calls "client.window_title.clear".
func (c *Client) ClientWindowTitleClear(ctx context.Context) (*ClientWindowTitleResult, error) {
	raw, err := c.CallRaw(ctx, MethodClientWindowTitleClear, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ClientWindowTitleResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodClientWindowTitleClear, Want: "client_window_title", Got: result.ResultType()}
	}
	return typed, nil
}

// ClientWindowTitleSet calls "client.window_title.set".
func (c *Client) ClientWindowTitleSet(ctx context.Context, params ClientWindowTitleSetParams) (*ClientWindowTitleResult, error) {
	raw, err := c.CallRaw(ctx, MethodClientWindowTitleSet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ClientWindowTitleResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodClientWindowTitleSet, Want: "client_window_title", Got: result.ResultType()}
	}
	return typed, nil
}

// CommandInvoke calls "command.invoke". The method answers with more than
// one result type, so the result is returned as a Result.
func (c *Client) CommandInvoke(ctx context.Context, params CommandInvokeParams) (Result, error) {
	raw, err := c.CallRaw(ctx, MethodCommandInvoke, params)
	if err != nil {
		return nil, err
	}
	return DecodeResult(raw)
}

// EventsSubscribe calls "events.subscribe" and keeps the connection open.
// Read the pushed events with (*Stream).NextEvent.
func (c *Client) EventsSubscribe(ctx context.Context, params EventsSubscribeParams) (*Stream, error) {
	return c.OpenStream(ctx, MethodEventsSubscribe, params)
}

// EventsWait calls "events.wait".
func (c *Client) EventsWait(ctx context.Context, params EventsWaitParams) (*WaitMatchedResult, error) {
	raw, err := c.CallRaw(ctx, MethodEventsWait, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WaitMatchedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodEventsWait, Want: "wait_matched", Got: result.ResultType()}
	}
	return typed, nil
}

// IntegrationInstall calls "integration.install".
func (c *Client) IntegrationInstall(ctx context.Context, params IntegrationInstallParams) (*IntegrationInstallResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodIntegrationInstall, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*IntegrationInstallResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodIntegrationInstall, Want: "integration_install", Got: result.ResultType()}
	}
	return typed, nil
}

// IntegrationList calls "integration.list".
func (c *Client) IntegrationList(ctx context.Context) (*IntegrationListResult, error) {
	raw, err := c.CallRaw(ctx, MethodIntegrationList, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*IntegrationListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodIntegrationList, Want: "integration_list", Got: result.ResultType()}
	}
	return typed, nil
}

// IntegrationUninstall calls "integration.uninstall".
func (c *Client) IntegrationUninstall(ctx context.Context, params IntegrationUninstallParams) (*IntegrationUninstallResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodIntegrationUninstall, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*IntegrationUninstallResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodIntegrationUninstall, Want: "integration_uninstall", Got: result.ResultType()}
	}
	return typed, nil
}

// LayoutApply calls "layout.apply".
func (c *Client) LayoutApply(ctx context.Context, params LayoutApplyParams) (*LayoutApplyResult, error) {
	raw, err := c.CallRaw(ctx, MethodLayoutApply, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*LayoutApplyResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodLayoutApply, Want: "layout_apply", Got: result.ResultType()}
	}
	return typed, nil
}

// LayoutExport calls "layout.export".
func (c *Client) LayoutExport(ctx context.Context, params LayoutExportParams) (*LayoutExportResult, error) {
	raw, err := c.CallRaw(ctx, MethodLayoutExport, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*LayoutExportResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodLayoutExport, Want: "layout_export", Got: result.ResultType()}
	}
	return typed, nil
}

// LayoutSetSplitRatio calls "layout.set_split_ratio".
func (c *Client) LayoutSetSplitRatio(ctx context.Context, params LayoutSetSplitRatioParams) (*LayoutSplitRatioSetResult, error) {
	raw, err := c.CallRaw(ctx, MethodLayoutSetSplitRatio, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*LayoutSplitRatioSetResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodLayoutSetSplitRatio, Want: "layout_split_ratio_set", Got: result.ResultType()}
	}
	return typed, nil
}

// NotificationShow calls "notification.show".
func (c *Client) NotificationShow(ctx context.Context, params NotificationShowParams) (*NotificationShowResult, error) {
	raw, err := c.CallRaw(ctx, MethodNotificationShow, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*NotificationShowResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodNotificationShow, Want: "notification_show", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneClearAgentAuthority calls "pane.clear_agent_authority".
func (c *Client) PaneClearAgentAuthority(ctx context.Context, params PaneClearAgentAuthorityParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneClearAgentAuthority, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneClearAgentAuthority, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneClose calls "pane.close".
func (c *Client) PaneClose(ctx context.Context, params PaneTarget) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneClose, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneClose, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneCopyMotion calls "pane.copy_motion".
func (c *Client) PaneCopyMotion(ctx context.Context, params PaneCopyMotionParams) (*PaneCopyMotionResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneCopyMotion, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneCopyMotionResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneCopyMotion, Want: "pane_copy_motion", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneCopySearch calls "pane.copy_search".
func (c *Client) PaneCopySearch(ctx context.Context, params PaneCopySearchParams) (*PaneCopySearchResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneCopySearch, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneCopySearchResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneCopySearch, Want: "pane_copy_search", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneCurrent calls "pane.current".
func (c *Client) PaneCurrent(ctx context.Context, params PaneCurrentParams) (*PaneCurrentResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneCurrent, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneCurrentResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneCurrent, Want: "pane_current", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneEdges calls "pane.edges".
func (c *Client) PaneEdges(ctx context.Context, params PaneEdgesParams) (*PaneEdgesResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneEdges, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneEdgesResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneEdges, Want: "pane_edges", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneEditScrollback calls "pane.edit_scrollback".
func (c *Client) PaneEditScrollback(ctx context.Context, params PaneTarget) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneEditScrollback, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneEditScrollback, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneFocus calls "pane.focus".
func (c *Client) PaneFocus(ctx context.Context, params PaneTarget) (*PaneInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneFocus, Want: "pane_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneFocusDirection calls "pane.focus_direction".
func (c *Client) PaneFocusDirection(ctx context.Context, params PaneFocusDirectionParams) (*PaneFocusDirectionResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneFocusDirection, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneFocusDirectionResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneFocusDirection, Want: "pane_focus_direction", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneGet calls "pane.get".
func (c *Client) PaneGet(ctx context.Context, params PaneTarget) (*PaneInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneGet, Want: "pane_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneGraphicsClear calls "pane.graphics.clear".
func (c *Client) PaneGraphicsClear(ctx context.Context, params PaneGraphicsClearParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGraphicsClear, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneGraphicsClear, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneGraphicsInfo calls "pane.graphics.info".
func (c *Client) PaneGraphicsInfo(ctx context.Context, params PaneTarget) (*PaneGraphicsInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGraphicsInfo, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneGraphicsInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneGraphicsInfo, Want: "pane_graphics_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneGraphicsSet calls "pane.graphics.set".
func (c *Client) PaneGraphicsSet(ctx context.Context, params PaneGraphicsSetParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneGraphicsSet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneGraphicsSet, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneInputSet calls "pane.input.set".
func (c *Client) PaneInputSet(ctx context.Context, params PaneInputSetParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneInputSet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneInputSet, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneLayout calls "pane.layout".
func (c *Client) PaneLayout(ctx context.Context, params PaneLayoutParams) (*PaneLayoutResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneLayout, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneLayoutResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneLayout, Want: "pane_layout", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneLinkActivate calls "pane.link.activate".
func (c *Client) PaneLinkActivate(ctx context.Context, params PaneLinkActivateParams) (*PaneLinkActivatedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneLinkActivate, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneLinkActivatedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneLinkActivate, Want: "pane_link_activated", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneList calls "pane.list".
func (c *Client) PaneList(ctx context.Context, params PaneListParams) (*PaneListResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneList, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneList, Want: "pane_list", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneMove calls "pane.move".
func (c *Client) PaneMove(ctx context.Context, params PaneMoveParams) (*PaneMoveResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneMove, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneMoveResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneMove, Want: "pane_move", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneNeighbor calls "pane.neighbor".
func (c *Client) PaneNeighbor(ctx context.Context, params PaneNeighborParams) (*PaneNeighborResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneNeighbor, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneNeighborResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneNeighbor, Want: "pane_neighbor", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneProcessInfo calls "pane.process_info".
func (c *Client) PaneProcessInfo(ctx context.Context, params PaneProcessInfoParams) (*PaneProcessInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneProcessInfo, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneProcessInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneProcessInfo, Want: "pane_process_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneRead calls "pane.read".
func (c *Client) PaneRead(ctx context.Context, params PaneReadParams) (*PaneReadResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneRead, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneReadResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneRead, Want: "pane_read", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneReleaseAgent calls "pane.release_agent".
func (c *Client) PaneReleaseAgent(ctx context.Context, params PaneReleaseAgentParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReleaseAgent, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneReleaseAgent, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneRename calls "pane.rename".
func (c *Client) PaneRename(ctx context.Context, params PaneRenameParams) (*PaneInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneRename, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneRename, Want: "pane_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneReportAgent calls "pane.report_agent".
func (c *Client) PaneReportAgent(ctx context.Context, params PaneReportAgentParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReportAgent, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneReportAgent, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneReportAgentSession calls "pane.report_agent_session".
func (c *Client) PaneReportAgentSession(ctx context.Context, params PaneReportAgentSessionParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReportAgentSession, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneReportAgentSession, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneReportMetadata calls "pane.report_metadata".
func (c *Client) PaneReportMetadata(ctx context.Context, params PaneReportMetadataParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneReportMetadata, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneReportMetadata, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneResize calls "pane.resize".
func (c *Client) PaneResize(ctx context.Context, params PaneResizeParams) (*PaneResizeResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneResize, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneResizeResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneResize, Want: "pane_resize", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneScroll calls "pane.scroll".
func (c *Client) PaneScroll(ctx context.Context, params PaneScrollParams) (*PaneInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneScroll, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneScroll, Want: "pane_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneSelectionRead calls "pane.selection.read".
func (c *Client) PaneSelectionRead(ctx context.Context, params PaneSelectionReadParams) (*PaneSelectionResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSelectionRead, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneSelectionResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneSelectionRead, Want: "pane_selection", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneSendInput calls "pane.send_input".
func (c *Client) PaneSendInput(ctx context.Context, params PaneSendInputParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSendInput, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneSendInput, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneSendKeys calls "pane.send_keys".
func (c *Client) PaneSendKeys(ctx context.Context, params PaneSendKeysParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSendKeys, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneSendKeys, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneSendText calls "pane.send_text".
func (c *Client) PaneSendText(ctx context.Context, params PaneSendTextParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSendText, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneSendText, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneSplit calls "pane.split".
func (c *Client) PaneSplit(ctx context.Context, params PaneSplitParams) (*PaneInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSplit, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneSplit, Want: "pane_info", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneSwap calls "pane.swap".
func (c *Client) PaneSwap(ctx context.Context, params PaneSwapParams) (*PaneSwapResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneSwap, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneSwapResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneSwap, Want: "pane_swap", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneWaitForOutput calls "pane.wait_for_output".
func (c *Client) PaneWaitForOutput(ctx context.Context, params PaneWaitForOutputParams) (*OutputMatchedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneWaitForOutput, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OutputMatchedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneWaitForOutput, Want: "output_matched", Got: result.ResultType()}
	}
	return typed, nil
}

// PaneZoom calls "pane.zoom".
func (c *Client) PaneZoom(ctx context.Context, params PaneZoomParams) (*PaneZoomResponseResult, error) {
	raw, err := c.CallRaw(ctx, MethodPaneZoom, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PaneZoomResponseResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPaneZoom, Want: "pane_zoom", Got: result.ResultType()}
	}
	return typed, nil
}

// Ping calls "ping".
func (c *Client) Ping(ctx context.Context) (*PongResult, error) {
	raw, err := c.CallRaw(ctx, MethodPing, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PongResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPing, Want: "pong", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginActionInvoke calls "plugin.action.invoke".
func (c *Client) PluginActionInvoke(ctx context.Context, params PluginActionInvokeParams) (*PluginActionInvokedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginActionInvoke, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginActionInvokedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginActionInvoke, Want: "plugin_action_invoked", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginActionList calls "plugin.action.list".
func (c *Client) PluginActionList(ctx context.Context, params PluginActionListParams) (*PluginActionListResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginActionList, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginActionListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginActionList, Want: "plugin_action_list", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginDisable calls "plugin.disable".
func (c *Client) PluginDisable(ctx context.Context, params PluginSetEnabledParams) (*PluginDisabledResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginDisable, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginDisabledResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginDisable, Want: "plugin_disabled", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginEnable calls "plugin.enable".
func (c *Client) PluginEnable(ctx context.Context, params PluginSetEnabledParams) (*PluginEnabledResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginEnable, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginEnabledResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginEnable, Want: "plugin_enabled", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginLink calls "plugin.link".
func (c *Client) PluginLink(ctx context.Context, params PluginLinkParams) (*PluginLinkedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginLink, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginLinkedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginLink, Want: "plugin_linked", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginList calls "plugin.list".
func (c *Client) PluginList(ctx context.Context, params PluginListParams) (*PluginListResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginList, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginList, Want: "plugin_list", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginLogList calls "plugin.log.list".
func (c *Client) PluginLogList(ctx context.Context, params PluginLogListParams) (*PluginLogListResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginLogList, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginLogListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginLogList, Want: "plugin_log_list", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginPaneClose calls "plugin.pane.close".
func (c *Client) PluginPaneClose(ctx context.Context, params PluginPaneCloseParams) (*PluginPaneClosedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginPaneClose, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginPaneClosedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginPaneClose, Want: "plugin_pane_closed", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginPaneFocus calls "plugin.pane.focus".
func (c *Client) PluginPaneFocus(ctx context.Context, params PluginPaneFocusParams) (*PluginPaneFocusedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginPaneFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginPaneFocusedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginPaneFocus, Want: "plugin_pane_focused", Got: result.ResultType()}
	}
	return typed, nil
}

// PluginPaneOpen calls "plugin.pane.open". The result is one of
// *PluginPaneOpenedResult or *OKResult.
func (c *Client) PluginPaneOpen(ctx context.Context, params PluginPaneOpenParams) (Result, error) {
	raw, err := c.CallRaw(ctx, MethodPluginPaneOpen, params)
	if err != nil {
		return nil, err
	}
	return DecodeResult(raw)
}

// PluginUnlink calls "plugin.unlink".
func (c *Client) PluginUnlink(ctx context.Context, params PluginUnlinkParams) (*PluginUnlinkedResult, error) {
	raw, err := c.CallRaw(ctx, MethodPluginUnlink, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*PluginUnlinkedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPluginUnlink, Want: "plugin_unlinked", Got: result.ResultType()}
	}
	return typed, nil
}

// PopupClose calls "popup.close".
func (c *Client) PopupClose(ctx context.Context) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodPopupClose, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodPopupClose, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// ProductAnnouncementDismiss calls "product_announcement.dismiss".
func (c *Client) ProductAnnouncementDismiss(ctx context.Context, params ProductAnnouncementDismissParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodProductAnnouncementDismiss, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodProductAnnouncementDismiss, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// ReleaseNotesDismiss calls "release_notes.dismiss".
func (c *Client) ReleaseNotesDismiss(ctx context.Context, params ReleaseNotesDismissParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodReleaseNotesDismiss, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodReleaseNotesDismiss, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// ServerAgentManifests calls "server.agent_manifests".
func (c *Client) ServerAgentManifests(ctx context.Context) (*AgentManifestStatusResult, error) {
	raw, err := c.CallRaw(ctx, MethodServerAgentManifests, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentManifestStatusResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodServerAgentManifests, Want: "agent_manifest_status", Got: result.ResultType()}
	}
	return typed, nil
}

// ServerLiveHandoff calls "server.live_handoff". The method answers with
// more than one result type, so the result is returned as a Result.
func (c *Client) ServerLiveHandoff(ctx context.Context, params ServerLiveHandoffParams) (Result, error) {
	raw, err := c.CallRaw(ctx, MethodServerLiveHandoff, params)
	if err != nil {
		return nil, err
	}
	return DecodeResult(raw)
}

// ServerReloadAgentManifests calls "server.reload_agent_manifests".
func (c *Client) ServerReloadAgentManifests(ctx context.Context) (*AgentManifestReloadResult, error) {
	raw, err := c.CallRaw(ctx, MethodServerReloadAgentManifests, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*AgentManifestReloadResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodServerReloadAgentManifests, Want: "agent_manifest_reload", Got: result.ResultType()}
	}
	return typed, nil
}

// ServerReloadConfig calls "server.reload_config".
func (c *Client) ServerReloadConfig(ctx context.Context) (*ConfigReloadResult, error) {
	raw, err := c.CallRaw(ctx, MethodServerReloadConfig, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*ConfigReloadResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodServerReloadConfig, Want: "config_reload", Got: result.ResultType()}
	}
	return typed, nil
}

// ServerStop calls "server.stop".
func (c *Client) ServerStop(ctx context.Context) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodServerStop, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodServerStop, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// SessionSnapshot calls "session.snapshot".
func (c *Client) SessionSnapshot(ctx context.Context) (*SessionSnapshotResult, error) {
	raw, err := c.CallRaw(ctx, MethodSessionSnapshot, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*SessionSnapshotResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodSessionSnapshot, Want: "session_snapshot", Got: result.ResultType()}
	}
	return typed, nil
}

// TabClose calls "tab.close".
func (c *Client) TabClose(ctx context.Context, params TabTarget) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabClose, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabClose, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// TabCreate calls "tab.create".
func (c *Client) TabCreate(ctx context.Context, params TabCreateParams) (*TabCreatedResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabCreate, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabCreatedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabCreate, Want: "tab_created", Got: result.ResultType()}
	}
	return typed, nil
}

// TabFocus calls "tab.focus".
func (c *Client) TabFocus(ctx context.Context, params TabTarget) (*TabInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabFocus, Want: "tab_info", Got: result.ResultType()}
	}
	return typed, nil
}

// TabGet calls "tab.get".
func (c *Client) TabGet(ctx context.Context, params TabTarget) (*TabInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabGet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabGet, Want: "tab_info", Got: result.ResultType()}
	}
	return typed, nil
}

// TabList calls "tab.list".
func (c *Client) TabList(ctx context.Context, params TabListParams) (*TabListResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabList, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabList, Want: "tab_list", Got: result.ResultType()}
	}
	return typed, nil
}

// TabMove calls "tab.move".
func (c *Client) TabMove(ctx context.Context, params TabMoveParams) (*TabListResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabMove, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabMove, Want: "tab_list", Got: result.ResultType()}
	}
	return typed, nil
}

// TabRename calls "tab.rename".
func (c *Client) TabRename(ctx context.Context, params TabRenameParams) (*TabInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodTabRename, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*TabInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodTabRename, Want: "tab_info", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceClose calls "workspace.close".
func (c *Client) WorkspaceClose(ctx context.Context, params WorkspaceCloseParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceClose, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceClose, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceCreate calls "workspace.create".
func (c *Client) WorkspaceCreate(ctx context.Context, params WorkspaceCreateParams) (*WorkspaceCreatedResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceCreate, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceCreatedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceCreate, Want: "workspace_created", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceFocus calls "workspace.focus".
func (c *Client) WorkspaceFocus(ctx context.Context, params WorkspaceTarget) (*WorkspaceInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceFocus, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceFocus, Want: "workspace_info", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceGet calls "workspace.get".
func (c *Client) WorkspaceGet(ctx context.Context, params WorkspaceTarget) (*WorkspaceInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceGet, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceGet, Want: "workspace_info", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceList calls "workspace.list".
func (c *Client) WorkspaceList(ctx context.Context) (*WorkspaceListResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceList, nil)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceList, Want: "workspace_list", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceMove calls "workspace.move".
func (c *Client) WorkspaceMove(ctx context.Context, params WorkspaceMoveParams) (*WorkspaceListResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceMove, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceMove, Want: "workspace_list", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceMoveBlock calls "workspace.move_block".
func (c *Client) WorkspaceMoveBlock(ctx context.Context, params WorkspaceMoveBlockParams) (*WorkspaceListResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceMoveBlock, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceMoveBlock, Want: "workspace_list", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceRename calls "workspace.rename".
func (c *Client) WorkspaceRename(ctx context.Context, params WorkspaceRenameParams) (*WorkspaceInfoResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceRename, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorkspaceInfoResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceRename, Want: "workspace_info", Got: result.ResultType()}
	}
	return typed, nil
}

// WorkspaceReportMetadata calls "workspace.report_metadata".
func (c *Client) WorkspaceReportMetadata(ctx context.Context, params WorkspaceReportMetadataParams) (*OKResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorkspaceReportMetadata, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*OKResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorkspaceReportMetadata, Want: "ok", Got: result.ResultType()}
	}
	return typed, nil
}

// WorktreeCreate calls "worktree.create".
func (c *Client) WorktreeCreate(ctx context.Context, params WorktreeCreateParams) (*WorktreeCreatedResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeCreate, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeCreatedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorktreeCreate, Want: "worktree_created", Got: result.ResultType()}
	}
	return typed, nil
}

// WorktreeList calls "worktree.list".
func (c *Client) WorktreeList(ctx context.Context, params WorktreeListParams) (*WorktreeListResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeList, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeListResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorktreeList, Want: "worktree_list", Got: result.ResultType()}
	}
	return typed, nil
}

// WorktreeOpen calls "worktree.open".
func (c *Client) WorktreeOpen(ctx context.Context, params WorktreeOpenParams) (*WorktreeOpenedResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeOpen, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeOpenedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorktreeOpen, Want: "worktree_opened", Got: result.ResultType()}
	}
	return typed, nil
}

// WorktreeRemove calls "worktree.remove".
func (c *Client) WorktreeRemove(ctx context.Context, params WorktreeRemoveParams) (*WorktreeRemovedResult, error) {
	raw, err := c.CallRaw(ctx, MethodWorktreeRemove, params)
	if err != nil {
		return nil, err
	}
	result, err := DecodeResult(raw)
	if err != nil {
		return nil, err
	}
	typed, ok := result.(*WorktreeRemovedResult)
	if !ok {
		return nil, &UnexpectedResultError{Method: MethodWorktreeRemove, Want: "worktree_removed", Got: result.ResultType()}
	}
	return typed, nil
}
