// Code generated by herdr-apigen. DO NOT EDIT.

package herdr

import (
	"encoding/json"
	"fmt"
)

type AgentInfo struct {
	Agent                  *string           `json:"agent,omitempty"`
	AgentSession           *AgentSessionInfo `json:"agent_session,omitempty"`
	AgentStatus            AgentStatus       `json:"agent_status"`
	Cwd                    *string           `json:"cwd,omitempty"`
	DisplayAgent           *string           `json:"display_agent,omitempty"`
	Focused                bool              `json:"focused"`
	ForegroundCwd          *string           `json:"foreground_cwd,omitempty"`
	InteractiveReady       *bool             `json:"interactive_ready,omitempty"`
	LaunchPending          *bool             `json:"launch_pending,omitempty"`
	Name                   *string           `json:"name,omitempty"`
	PaneID                 string            `json:"pane_id"`
	Revision               uint64            `json:"revision"`
	ScreenDetectionSkipped *bool             `json:"screen_detection_skipped,omitempty"`
	StateChangeSeq         *uint64           `json:"state_change_seq,omitempty"`
	StateLabels            map[string]string `json:"state_labels,omitempty"`
	TabID                  string            `json:"tab_id"`
	TerminalID             string            `json:"terminal_id"`
	TerminalTitle          *string           `json:"terminal_title,omitempty"`
	TerminalTitleStripped  *string           `json:"terminal_title_stripped,omitempty"`
	Title                  *string           `json:"title,omitempty"`
	Tokens                 map[string]string `json:"tokens,omitempty"`
	WorkspaceID            string            `json:"workspace_id"`
}

type AgentManifestInfo struct {
	ActiveVersion                *string `json:"active_version,omitempty"`
	Agent                        string  `json:"agent"`
	CachedRemoteVersion          *string `json:"cached_remote_version,omitempty"`
	LocalOverrideShadowingRemote bool    `json:"local_override_shadowing_remote"`
	RemoteLastCheckedUnix        *uint64 `json:"remote_last_checked_unix,omitempty"`
	RemoteUpdateError            *string `json:"remote_update_error,omitempty"`
	RemoteUpdateResult           *string `json:"remote_update_result,omitempty"`
	Source                       string  `json:"source"`
	SourceKind                   string  `json:"source_kind"`
	Warning                      *string `json:"warning,omitempty"`
}

type AgentPromptParams struct {
	Target string                  `json:"target"`
	Text   string                  `json:"text"`
	Wait   *AgentPromptWaitOptions `json:"wait,omitempty"`
}

type AgentPromptWaitOptions struct {
	TimeoutMs *uint64       `json:"timeout_ms,omitempty"`
	Until     []AgentStatus `json:"until,omitempty"`
}

type AgentReadParams struct {
	Format    ReadFormat `json:"format,omitempty"`
	Lines     *uint32    `json:"lines,omitempty"`
	Source    ReadSource `json:"source"`
	StripANSI *bool      `json:"strip_ansi,omitempty"`
	Target    string     `json:"target"`
}

type AgentRenameParams struct {
	Name   *string `json:"name,omitempty"`
	Target string  `json:"target"`
}

type AgentSendKeysParams struct {
	Keys   []string `json:"keys"`
	Target string   `json:"target"`
}

type AgentSessionInfo struct {
	Agent  string              `json:"agent"`
	Kind   AgentSessionRefKind `json:"kind"`
	Source string              `json:"source"`
	Value  string              `json:"value"`
}

type AgentSessionRefKind string

// AgentSessionRefKind values.
const (
	AgentSessionRefKindID   AgentSessionRefKind = "id"
	AgentSessionRefKindPath AgentSessionRefKind = "path"
)

type AgentStartParams struct {
	Args   []string `json:"args,omitempty"`
	Kind   string   `json:"kind"`
	Name   string   `json:"name"`
	PaneID string   `json:"pane_id"`

	// Startup timeout in milliseconds. Values must be greater than 3000
	// and at most 300000.
	TimeoutMs *uint64 `json:"timeout_ms,omitempty"`
}

type AgentStatus string

// AgentStatus values.
const (
	AgentStatusIdle    AgentStatus = "idle"
	AgentStatusWorking AgentStatus = "working"
	AgentStatusBlocked AgentStatus = "blocked"
	AgentStatusDone    AgentStatus = "done"
	AgentStatusUnknown AgentStatus = "unknown"
)

type AgentTarget struct {
	Target string `json:"target"`
}

type AgentViewBuiltinField string

// AgentViewBuiltinField values.
const (
	AgentViewBuiltinFieldStatus         AgentViewBuiltinField = "status"
	AgentViewBuiltinFieldWorkspaceID    AgentViewBuiltinField = "workspace_id"
	AgentViewBuiltinFieldTabID          AgentViewBuiltinField = "tab_id"
	AgentViewBuiltinFieldPaneID         AgentViewBuiltinField = "pane_id"
	AgentViewBuiltinFieldAgent          AgentViewBuiltinField = "agent"
	AgentViewBuiltinFieldSeen           AgentViewBuiltinField = "seen"
	AgentViewBuiltinFieldStateChangeSeq AgentViewBuiltinField = "state_change_seq"
)

type AgentViewBuiltinSortField string

// AgentViewBuiltinSortField values.
const (
	AgentViewBuiltinSortFieldWorkspaceOrder AgentViewBuiltinSortField = "workspace_order"
	AgentViewBuiltinSortFieldTabOrder       AgentViewBuiltinSortField = "tab_order"
	AgentViewBuiltinSortFieldPaneOrder      AgentViewBuiltinSortField = "pane_order"
	AgentViewBuiltinSortFieldAttention      AgentViewBuiltinSortField = "attention"
	AgentViewBuiltinSortFieldStatus         AgentViewBuiltinSortField = "status"
	AgentViewBuiltinSortFieldAgent          AgentViewBuiltinSortField = "agent"
	AgentViewBuiltinSortFieldSeen           AgentViewBuiltinSortField = "seen"
	AgentViewBuiltinSortFieldStateChangeSeq AgentViewBuiltinSortField = "state_change_seq"
)

type AgentViewClearParams struct {
	Source *string `json:"source,omitempty"`
}

type AgentViewContext string

// AgentViewContext values.
const (
	AgentViewContextCurrentWorkspaceID AgentViewContext = "current_workspace_id"
	AgentViewContextCurrentTabID       AgentViewContext = "current_tab_id"
)

// AgentViewFilter is a union of the types below, selected by the "op"
// field.
type AgentViewFilter interface {
	isAgentViewFilter()
}

func decodeAgentViewFilter(data []byte) (AgentViewFilter, error) {
	var head struct {
		Tag string `json:"op"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Tag {
	case "all":
		var value AgentViewFilterAll
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "any":
		var value AgentViewFilterAny
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "not":
		var value AgentViewFilterNot
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "eq":
		var value AgentViewFilterEq
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "in":
		var value AgentViewFilterIn
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "exists":
		var value AgentViewFilterExists
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("herdr: unknown AgentViewFilter %q", head.Tag)
}

// AgentViewFilterAll is the "all" variant of AgentViewFilter.
type AgentViewFilterAll struct {
	Filters []AgentViewFilter `json:"filters"`
}

func (AgentViewFilterAll) isAgentViewFilter() {}

// MarshalJSON writes the object with its "op" field.
func (v AgentViewFilterAll) MarshalJSON() ([]byte, error) {
	type alias AgentViewFilterAll
	return json.Marshal(struct {
		Op string `json:"op"`
		alias
	}{Op: "all", alias: alias(v)})
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *AgentViewFilterAll) UnmarshalJSON(data []byte) error {
	type alias AgentViewFilterAll
	var aux struct {
		alias
		Filters []json.RawMessage `json:"filters"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = AgentViewFilterAll(aux.alias)
	if len(aux.Filters) > 0 {
		v.Filters = make([]AgentViewFilter, 0, len(aux.Filters))
		for _, item := range aux.Filters {
			decoded, err := decodeAgentViewFilter(item)
			if err != nil {
				return err
			}
			v.Filters = append(v.Filters, decoded)
		}
	}
	return nil
}

// AgentViewFilterAny is the "any" variant of AgentViewFilter.
type AgentViewFilterAny struct {
	Filters []AgentViewFilter `json:"filters"`
}

func (AgentViewFilterAny) isAgentViewFilter() {}

// MarshalJSON writes the object with its "op" field.
func (v AgentViewFilterAny) MarshalJSON() ([]byte, error) {
	type alias AgentViewFilterAny
	return json.Marshal(struct {
		Op string `json:"op"`
		alias
	}{Op: "any", alias: alias(v)})
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *AgentViewFilterAny) UnmarshalJSON(data []byte) error {
	type alias AgentViewFilterAny
	var aux struct {
		alias
		Filters []json.RawMessage `json:"filters"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = AgentViewFilterAny(aux.alias)
	if len(aux.Filters) > 0 {
		v.Filters = make([]AgentViewFilter, 0, len(aux.Filters))
		for _, item := range aux.Filters {
			decoded, err := decodeAgentViewFilter(item)
			if err != nil {
				return err
			}
			v.Filters = append(v.Filters, decoded)
		}
	}
	return nil
}

// AgentViewFilterEq is the "eq" variant of AgentViewFilter.
type AgentViewFilterEq struct {
	Field AgentViewField `json:"field"`
	Value AgentViewValue `json:"value"`
}

func (AgentViewFilterEq) isAgentViewFilter() {}

// MarshalJSON writes the object with its "op" field.
func (v AgentViewFilterEq) MarshalJSON() ([]byte, error) {
	type alias AgentViewFilterEq
	return json.Marshal(struct {
		Op string `json:"op"`
		alias
	}{Op: "eq", alias: alias(v)})
}

// AgentViewFilterExists is the "exists" variant of AgentViewFilter.
type AgentViewFilterExists struct {
	Field AgentViewField `json:"field"`
}

func (AgentViewFilterExists) isAgentViewFilter() {}

// MarshalJSON writes the object with its "op" field.
func (v AgentViewFilterExists) MarshalJSON() ([]byte, error) {
	type alias AgentViewFilterExists
	return json.Marshal(struct {
		Op string `json:"op"`
		alias
	}{Op: "exists", alias: alias(v)})
}

// AgentViewFilterIn is the "in" variant of AgentViewFilter.
type AgentViewFilterIn struct {
	Field  AgentViewField   `json:"field"`
	Values []AgentViewValue `json:"values"`
}

func (AgentViewFilterIn) isAgentViewFilter() {}

// MarshalJSON writes the object with its "op" field.
func (v AgentViewFilterIn) MarshalJSON() ([]byte, error) {
	type alias AgentViewFilterIn
	return json.Marshal(struct {
		Op string `json:"op"`
		alias
	}{Op: "in", alias: alias(v)})
}

// AgentViewFilterNot is the "not" variant of AgentViewFilter.
type AgentViewFilterNot struct {
	Filter AgentViewFilter `json:"filter"`
}

func (AgentViewFilterNot) isAgentViewFilter() {}

// MarshalJSON writes the object with its "op" field.
func (v AgentViewFilterNot) MarshalJSON() ([]byte, error) {
	type alias AgentViewFilterNot
	return json.Marshal(struct {
		Op string `json:"op"`
		alias
	}{Op: "not", alias: alias(v)})
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *AgentViewFilterNot) UnmarshalJSON(data []byte) error {
	type alias AgentViewFilterNot
	var aux struct {
		alias
		Filter json.RawMessage `json:"filter"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = AgentViewFilterNot(aux.alias)
	if len(aux.Filter) > 0 && string(aux.Filter) != "null" {
		decoded, err := decodeAgentViewFilter(aux.Filter)
		if err != nil {
			return err
		}
		v.Filter = decoded
	}
	return nil
}

type AgentViewSetParams struct {
	Filter AgentViewFilter `json:"filter,omitempty"`
	Label  *string         `json:"label,omitempty"`
	Sort   []AgentViewSort `json:"sort,omitempty"`
	Source string          `json:"source"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *AgentViewSetParams) UnmarshalJSON(data []byte) error {
	type alias AgentViewSetParams
	var aux struct {
		alias
		Filter json.RawMessage `json:"filter,omitempty"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = AgentViewSetParams(aux.alias)
	if len(aux.Filter) > 0 && string(aux.Filter) != "null" {
		decoded, err := decodeAgentViewFilter(aux.Filter)
		if err != nil {
			return err
		}
		v.Filter = decoded
	}
	return nil
}

type AgentViewSort struct {
	Field AgentViewSortField `json:"field"`
	Order AgentViewSortOrder `json:"order,omitempty"`
}

type AgentViewSortOrder string

// AgentViewSortOrder values.
const (
	AgentViewSortOrderAsc  AgentViewSortOrder = "asc"
	AgentViewSortOrderDesc AgentViewSortOrder = "desc"
)

type AgentWaitParams struct {
	Target    string        `json:"target"`
	TimeoutMs *uint64       `json:"timeout_ms,omitempty"`
	Until     []AgentStatus `json:"until,omitempty"`
}

// Updates whether the requesting client shell receives and controls pane
// presentation.
type ClientShellSurfaceSetParams struct {
	Active bool `json:"active"`
}

type ClientWindowTitleReason string

// ClientWindowTitleReason values.
const (
	ClientWindowTitleReasonSet                ClientWindowTitleReason = "set"
	ClientWindowTitleReasonCleared            ClientWindowTitleReason = "cleared"
	ClientWindowTitleReasonNoForegroundClient ClientWindowTitleReason = "no_foreground_client"
)

type ClientWindowTitleSetParams struct {
	Title string `json:"title"`
}

type CommandInvokeParams struct {
	// Opaque endpoint-issued command identifier from the client-shell
	// projection.
	CommandID string  `json:"command_id"`
	PaneID    *string `json:"pane_id,omitempty"`

	// Client-owned selection coordinates, validated against the pane's
	// content revision.
	Selection   *PaneSelectionReadParams `json:"selection,omitempty"`
	TabID       *string                  `json:"tab_id,omitempty"`
	WorkspaceID *string                  `json:"workspace_id,omitempty"`
}

type ConfigReloadStatus string

// ConfigReloadStatus values.
const (
	ConfigReloadStatusApplied ConfigReloadStatus = "applied"
	ConfigReloadStatusPartial ConfigReloadStatus = "partial"
	ConfigReloadStatusFailed  ConfigReloadStatus = "failed"
)

type EmptyParams struct{}

type ErrorBody struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// EventMatch is a union of the types below, selected by the "event" field.
type EventMatch interface {
	isEventMatch()
}

func decodeEventMatch(data []byte) (EventMatch, error) {
	var head struct {
		Tag string `json:"event"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Tag {
	case "workspace_created":
		var value EventMatchWorkspaceCreated
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_updated":
		var value EventMatchWorkspaceUpdated
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_closed":
		var value EventMatchWorkspaceClosed
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_renamed":
		var value EventMatchWorkspaceRenamed
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_moved":
		var value EventMatchWorkspaceMoved
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace_focused":
		var value EventMatchWorkspaceFocused
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_created":
		var value EventMatchTabCreated
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_closed":
		var value EventMatchTabClosed
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_renamed":
		var value EventMatchTabRenamed
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_moved":
		var value EventMatchTabMoved
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab_focused":
		var value EventMatchTabFocused
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_created":
		var value EventMatchPaneCreated
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_closed":
		var value EventMatchPaneClosed
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_focused":
		var value EventMatchPaneFocused
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_moved":
		var value EventMatchPaneMoved
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_output_changed":
		var value EventMatchPaneOutputChanged
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_exited":
		var value EventMatchPaneExited
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_agent_detected":
		var value EventMatchPaneAgentDetected
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane_agent_status_changed":
		var value EventMatchPaneAgentStatusChanged
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("herdr: unknown EventMatch %q", head.Tag)
}

// EventMatchPaneAgentDetected is the "pane_agent_detected" variant of
// EventMatch.
type EventMatchPaneAgentDetected struct {
	Agent  *string `json:"agent,omitempty"`
	PaneID string  `json:"pane_id"`
}

func (EventMatchPaneAgentDetected) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneAgentDetected) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneAgentDetected
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_agent_detected", alias: alias(v)})
}

// EventMatchPaneAgentStatusChanged is the "pane_agent_status_changed"
// variant of EventMatch.
type EventMatchPaneAgentStatusChanged struct {
	AgentStatus AgentStatus `json:"agent_status"`
	PaneID      string      `json:"pane_id"`
}

func (EventMatchPaneAgentStatusChanged) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneAgentStatusChanged) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneAgentStatusChanged
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_agent_status_changed", alias: alias(v)})
}

// EventMatchPaneClosed is the "pane_closed" variant of EventMatch.
type EventMatchPaneClosed struct {
	PaneID string `json:"pane_id"`
}

func (EventMatchPaneClosed) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneClosed) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneClosed
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_closed", alias: alias(v)})
}

// EventMatchPaneCreated is the "pane_created" variant of EventMatch.
type EventMatchPaneCreated struct {
	PaneID      *string `json:"pane_id,omitempty"`
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

func (EventMatchPaneCreated) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneCreated) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneCreated
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_created", alias: alias(v)})
}

// EventMatchPaneExited is the "pane_exited" variant of EventMatch.
type EventMatchPaneExited struct {
	PaneID string `json:"pane_id"`
}

func (EventMatchPaneExited) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneExited) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneExited
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_exited", alias: alias(v)})
}

// EventMatchPaneFocused is the "pane_focused" variant of EventMatch.
type EventMatchPaneFocused struct {
	PaneID string `json:"pane_id"`
}

func (EventMatchPaneFocused) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneFocused) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneFocused
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_focused", alias: alias(v)})
}

// EventMatchPaneMoved is the "pane_moved" variant of EventMatch.
type EventMatchPaneMoved struct {
	PaneID string `json:"pane_id"`
}

func (EventMatchPaneMoved) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneMoved) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneMoved
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_moved", alias: alias(v)})
}

// EventMatchPaneOutputChanged is the "pane_output_changed" variant of
// EventMatch.
type EventMatchPaneOutputChanged struct {
	MinRevision *uint64 `json:"min_revision,omitempty"`
	PaneID      string  `json:"pane_id"`
}

func (EventMatchPaneOutputChanged) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchPaneOutputChanged) MarshalJSON() ([]byte, error) {
	type alias EventMatchPaneOutputChanged
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "pane_output_changed", alias: alias(v)})
}

// EventMatchTabClosed is the "tab_closed" variant of EventMatch.
type EventMatchTabClosed struct {
	TabID string `json:"tab_id"`
}

func (EventMatchTabClosed) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchTabClosed) MarshalJSON() ([]byte, error) {
	type alias EventMatchTabClosed
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "tab_closed", alias: alias(v)})
}

// EventMatchTabCreated is the "tab_created" variant of EventMatch.
type EventMatchTabCreated struct {
	TabID       *string `json:"tab_id,omitempty"`
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

func (EventMatchTabCreated) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchTabCreated) MarshalJSON() ([]byte, error) {
	type alias EventMatchTabCreated
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "tab_created", alias: alias(v)})
}

// EventMatchTabFocused is the "tab_focused" variant of EventMatch.
type EventMatchTabFocused struct {
	TabID string `json:"tab_id"`
}

func (EventMatchTabFocused) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchTabFocused) MarshalJSON() ([]byte, error) {
	type alias EventMatchTabFocused
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "tab_focused", alias: alias(v)})
}

// EventMatchTabMoved is the "tab_moved" variant of EventMatch.
type EventMatchTabMoved struct {
	TabID string `json:"tab_id"`
}

func (EventMatchTabMoved) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchTabMoved) MarshalJSON() ([]byte, error) {
	type alias EventMatchTabMoved
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "tab_moved", alias: alias(v)})
}

// EventMatchTabRenamed is the "tab_renamed" variant of EventMatch.
type EventMatchTabRenamed struct {
	Label *string `json:"label,omitempty"`
	TabID string  `json:"tab_id"`
}

func (EventMatchTabRenamed) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchTabRenamed) MarshalJSON() ([]byte, error) {
	type alias EventMatchTabRenamed
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "tab_renamed", alias: alias(v)})
}

// EventMatchWorkspaceClosed is the "workspace_closed" variant of
// EventMatch.
type EventMatchWorkspaceClosed struct {
	WorkspaceID string `json:"workspace_id"`
}

func (EventMatchWorkspaceClosed) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchWorkspaceClosed) MarshalJSON() ([]byte, error) {
	type alias EventMatchWorkspaceClosed
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "workspace_closed", alias: alias(v)})
}

// EventMatchWorkspaceCreated is the "workspace_created" variant of
// EventMatch.
type EventMatchWorkspaceCreated struct {
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

func (EventMatchWorkspaceCreated) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchWorkspaceCreated) MarshalJSON() ([]byte, error) {
	type alias EventMatchWorkspaceCreated
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "workspace_created", alias: alias(v)})
}

// EventMatchWorkspaceFocused is the "workspace_focused" variant of
// EventMatch.
type EventMatchWorkspaceFocused struct {
	WorkspaceID string `json:"workspace_id"`
}

func (EventMatchWorkspaceFocused) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchWorkspaceFocused) MarshalJSON() ([]byte, error) {
	type alias EventMatchWorkspaceFocused
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "workspace_focused", alias: alias(v)})
}

// EventMatchWorkspaceMoved is the "workspace_moved" variant of EventMatch.
type EventMatchWorkspaceMoved struct {
	WorkspaceID string `json:"workspace_id"`
}

func (EventMatchWorkspaceMoved) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchWorkspaceMoved) MarshalJSON() ([]byte, error) {
	type alias EventMatchWorkspaceMoved
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "workspace_moved", alias: alias(v)})
}

// EventMatchWorkspaceRenamed is the "workspace_renamed" variant of
// EventMatch.
type EventMatchWorkspaceRenamed struct {
	Label       *string `json:"label,omitempty"`
	WorkspaceID string  `json:"workspace_id"`
}

func (EventMatchWorkspaceRenamed) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchWorkspaceRenamed) MarshalJSON() ([]byte, error) {
	type alias EventMatchWorkspaceRenamed
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "workspace_renamed", alias: alias(v)})
}

// EventMatchWorkspaceUpdated is the "workspace_updated" variant of
// EventMatch.
type EventMatchWorkspaceUpdated struct {
	WorkspaceID string `json:"workspace_id"`
}

func (EventMatchWorkspaceUpdated) isEventMatch() {}

// MarshalJSON writes the object with its "event" field.
func (v EventMatchWorkspaceUpdated) MarshalJSON() ([]byte, error) {
	type alias EventMatchWorkspaceUpdated
	return json.Marshal(struct {
		Event string `json:"event"`
		alias
	}{Event: "workspace_updated", alias: alias(v)})
}

type EventsSubscribeParams struct {
	Subscriptions []Subscription `json:"subscriptions"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *EventsSubscribeParams) UnmarshalJSON(data []byte) error {
	type alias EventsSubscribeParams
	var aux struct {
		alias
		Subscriptions []json.RawMessage `json:"subscriptions"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = EventsSubscribeParams(aux.alias)
	if len(aux.Subscriptions) > 0 {
		v.Subscriptions = make([]Subscription, 0, len(aux.Subscriptions))
		for _, item := range aux.Subscriptions {
			decoded, err := decodeSubscription(item)
			if err != nil {
				return err
			}
			v.Subscriptions = append(v.Subscriptions, decoded)
		}
	}
	return nil
}

type EventsWaitParams struct {
	MatchEvent EventMatch `json:"match_event"`
	TimeoutMs  *uint64    `json:"timeout_ms,omitempty"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *EventsWaitParams) UnmarshalJSON(data []byte) error {
	type alias EventsWaitParams
	var aux struct {
		alias
		MatchEvent json.RawMessage `json:"match_event"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = EventsWaitParams(aux.alias)
	if len(aux.MatchEvent) > 0 && string(aux.MatchEvent) != "null" {
		decoded, err := decodeEventMatch(aux.MatchEvent)
		if err != nil {
			return err
		}
		v.MatchEvent = decoded
	}
	return nil
}

type InstalledPluginInfo struct {
	Actions         []PluginManifestAction      `json:"actions,omitempty"`
	Build           []PluginManifestBuild       `json:"build,omitempty"`
	Description     *string                     `json:"description,omitempty"`
	Enabled         bool                        `json:"enabled"`
	Events          []PluginManifestEventHook   `json:"events,omitempty"`
	LinkHandlers    []PluginManifestLinkHandler `json:"link_handlers,omitempty"`
	ManifestPath    string                      `json:"manifest_path"`
	MinHerdrVersion string                      `json:"min_herdr_version,omitempty"`
	Name            string                      `json:"name"`
	Panes           []PluginManifestPane        `json:"panes,omitempty"`
	Platforms       []PluginPlatform            `json:"platforms,omitempty"`
	PluginID        string                      `json:"plugin_id"`
	PluginRoot      string                      `json:"plugin_root"`
	Source          *PluginSourceInfo           `json:"source,omitempty"`
	Startup         []PluginManifestStartup     `json:"startup,omitempty"`
	Version         string                      `json:"version"`

	// Warnings collected at link time or on registry load (e.g. unknown
	// event names, missing manifest file). Non-fatal — the entry is kept
	// and surfaced by plugin.list.
	Warnings []string `json:"warnings,omitempty"`
}

type IntegrationInfo struct {
	Available bool              `json:"available"`
	Command   string            `json:"command"`
	Label     string            `json:"label"`
	State     IntegrationState  `json:"state"`
	Target    IntegrationTarget `json:"target"`
}

type IntegrationInstallParams struct {
	Target IntegrationTarget `json:"target"`
}

type IntegrationInstallResult struct {
	Messages []string `json:"messages"`
}

type IntegrationState string

// IntegrationState values.
const (
	IntegrationStateNotInstalled IntegrationState = "not_installed"
	IntegrationStateCurrent      IntegrationState = "current"
	IntegrationStateOutdated     IntegrationState = "outdated"
)

type IntegrationTarget string

// IntegrationTarget values.
const (
	IntegrationTargetPi             IntegrationTarget = "pi"
	IntegrationTargetOmp            IntegrationTarget = "omp"
	IntegrationTargetClaude         IntegrationTarget = "claude"
	IntegrationTargetCodex          IntegrationTarget = "codex"
	IntegrationTargetCopilot        IntegrationTarget = "copilot"
	IntegrationTargetDevin          IntegrationTarget = "devin"
	IntegrationTargetDroid          IntegrationTarget = "droid"
	IntegrationTargetKimi           IntegrationTarget = "kimi"
	IntegrationTargetOpencode       IntegrationTarget = "opencode"
	IntegrationTargetKilo           IntegrationTarget = "kilo"
	IntegrationTargetHermes         IntegrationTarget = "hermes"
	IntegrationTargetQodercli       IntegrationTarget = "qodercli"
	IntegrationTargetQwen           IntegrationTarget = "qwen"
	IntegrationTargetCursor         IntegrationTarget = "cursor"
	IntegrationTargetMastracode     IntegrationTarget = "mastracode"
	IntegrationTargetAntigravityCLI IntegrationTarget = "antigravity_cli"
	IntegrationTargetGrok           IntegrationTarget = "grok"
)

type IntegrationUninstallParams struct {
	Target IntegrationTarget `json:"target"`
}

type IntegrationUninstallResult struct {
	Messages []string `json:"messages"`
}

type LayoutApplyParams struct {
	Focus       *bool      `json:"focus,omitempty"`
	Root        LayoutNode `json:"root"`
	TabID       *string    `json:"tab_id,omitempty"`
	TabLabel    *string    `json:"tab_label,omitempty"`
	WorkspaceID *string    `json:"workspace_id,omitempty"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *LayoutApplyParams) UnmarshalJSON(data []byte) error {
	type alias LayoutApplyParams
	var aux struct {
		alias
		Root json.RawMessage `json:"root"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = LayoutApplyParams(aux.alias)
	if len(aux.Root) > 0 && string(aux.Root) != "null" {
		decoded, err := decodeLayoutNode(aux.Root)
		if err != nil {
			return err
		}
		v.Root = decoded
	}
	return nil
}

type LayoutDescription struct {
	FocusedPaneID string     `json:"focused_pane_id"`
	Root          LayoutNode `json:"root"`
	TabID         string     `json:"tab_id"`
	WorkspaceID   string     `json:"workspace_id"`
	Zoomed        bool       `json:"zoomed"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *LayoutDescription) UnmarshalJSON(data []byte) error {
	type alias LayoutDescription
	var aux struct {
		alias
		Root json.RawMessage `json:"root"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = LayoutDescription(aux.alias)
	if len(aux.Root) > 0 && string(aux.Root) != "null" {
		decoded, err := decodeLayoutNode(aux.Root)
		if err != nil {
			return err
		}
		v.Root = decoded
	}
	return nil
}

type LayoutExportParams struct {
	PaneID *string `json:"pane_id,omitempty"`
	TabID  *string `json:"tab_id,omitempty"`
}

// LayoutNode is a union of the types below, selected by the "type" field.
type LayoutNode interface {
	isLayoutNode()
}

func decodeLayoutNode(data []byte) (LayoutNode, error) {
	var head struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Tag {
	case "pane":
		var value LayoutNodePane
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "split":
		var value LayoutNodeSplit
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("herdr: unknown LayoutNode %q", head.Tag)
}

// LayoutNodePane is the "pane" variant of LayoutNode.
type LayoutNodePane struct {
	Command []string          `json:"command,omitempty"`
	Cwd     *string           `json:"cwd,omitempty"`
	Env     map[string]string `json:"env,omitempty"`
	Label   *string           `json:"label,omitempty"`
	PaneID  *string           `json:"pane_id,omitempty"`
}

func (LayoutNodePane) isLayoutNode() {}

// MarshalJSON writes the object with its "type" field.
func (v LayoutNodePane) MarshalJSON() ([]byte, error) {
	type alias LayoutNodePane
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane", alias: alias(v)})
}

// LayoutNodeSplit is the "split" variant of LayoutNode.
type LayoutNodeSplit struct {
	Direction SplitDirection `json:"direction"`
	First     LayoutNode     `json:"first"`
	Ratio     float64        `json:"ratio"`
	Second    LayoutNode     `json:"second"`
}

func (LayoutNodeSplit) isLayoutNode() {}

// MarshalJSON writes the object with its "type" field.
func (v LayoutNodeSplit) MarshalJSON() ([]byte, error) {
	type alias LayoutNodeSplit
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "split", alias: alias(v)})
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *LayoutNodeSplit) UnmarshalJSON(data []byte) error {
	type alias LayoutNodeSplit
	var aux struct {
		alias
		First  json.RawMessage `json:"first"`
		Second json.RawMessage `json:"second"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = LayoutNodeSplit(aux.alias)
	if len(aux.First) > 0 && string(aux.First) != "null" {
		decoded, err := decodeLayoutNode(aux.First)
		if err != nil {
			return err
		}
		v.First = decoded
	}
	if len(aux.Second) > 0 && string(aux.Second) != "null" {
		decoded, err := decodeLayoutNode(aux.Second)
		if err != nil {
			return err
		}
		v.Second = decoded
	}
	return nil
}

type LayoutSetSplitRatioParams struct {
	PaneID *string `json:"pane_id,omitempty"`
	Path   []bool  `json:"path"`
	Ratio  float64 `json:"ratio"`
	TabID  *string `json:"tab_id,omitempty"`
}

// LayoutUpdatedSubscription is the "layout.updated" variant of
// Subscription.
type LayoutUpdatedSubscription struct{}

func (LayoutUpdatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v LayoutUpdatedSubscription) MarshalJSON() ([]byte, error) {
	type alias LayoutUpdatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "layout.updated", alias: alias(v)})
}

type NotificationShowParams struct {
	Body     *string               `json:"body,omitempty"`
	Position *ToastHerdrPosition   `json:"position,omitempty"`
	Sound    NotificationShowSound `json:"sound,omitempty"`
	Title    string                `json:"title"`
}

type NotificationShowReason string

// NotificationShowReason values.
const (
	NotificationShowReasonShown              NotificationShowReason = "shown"
	NotificationShowReasonDisabled           NotificationShowReason = "disabled"
	NotificationShowReasonRateLimited        NotificationShowReason = "rate_limited"
	NotificationShowReasonNoForegroundClient NotificationShowReason = "no_foreground_client"
	NotificationShowReasonBusy               NotificationShowReason = "busy"
)

type NotificationShowSound string

// NotificationShowSound values.
const (
	NotificationShowSoundNone    NotificationShowSound = "none"
	NotificationShowSoundDone    NotificationShowSound = "done"
	NotificationShowSoundRequest NotificationShowSound = "request"
)

// OutputMatch is a union of the types below, selected by the "type" field.
type OutputMatch interface {
	isOutputMatch()
}

func decodeOutputMatch(data []byte) (OutputMatch, error) {
	var head struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Tag {
	case "substring":
		var value OutputMatchSubstring
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "regex":
		var value OutputMatchRegex
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("herdr: unknown OutputMatch %q", head.Tag)
}

// OutputMatchRegex is the "regex" variant of OutputMatch.
type OutputMatchRegex struct {
	Value string `json:"value"`
}

func (OutputMatchRegex) isOutputMatch() {}

// MarshalJSON writes the object with its "type" field.
func (v OutputMatchRegex) MarshalJSON() ([]byte, error) {
	type alias OutputMatchRegex
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "regex", alias: alias(v)})
}

// OutputMatchSubstring is the "substring" variant of OutputMatch.
type OutputMatchSubstring struct {
	Value string `json:"value"`
}

func (OutputMatchSubstring) isOutputMatch() {}

// MarshalJSON writes the object with its "type" field.
func (v OutputMatchSubstring) MarshalJSON() ([]byte, error) {
	type alias OutputMatchSubstring
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "substring", alias: alias(v)})
}

// PaneAgentDetectedSubscription is the "pane.agent_detected" variant of
// Subscription.
type PaneAgentDetectedSubscription struct{}

func (PaneAgentDetectedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneAgentDetectedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneAgentDetectedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.agent_detected", alias: alias(v)})
}

type PaneAgentState string

// PaneAgentState values.
const (
	PaneAgentStateIdle    PaneAgentState = "idle"
	PaneAgentStateWorking PaneAgentState = "working"
	PaneAgentStateBlocked PaneAgentState = "blocked"
	PaneAgentStateUnknown PaneAgentState = "unknown"
)

// PaneAgentStatusChangedSubscription is the "pane.agent_status_changed"
// variant of Subscription.
type PaneAgentStatusChangedSubscription struct {
	AgentStatus *AgentStatus `json:"agent_status,omitempty"`
	PaneID      string       `json:"pane_id"`
}

func (PaneAgentStatusChangedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneAgentStatusChangedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneAgentStatusChangedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.agent_status_changed", alias: alias(v)})
}

type PaneClearAgentAuthorityParams struct {
	PaneID string  `json:"pane_id"`
	Seq    *uint64 `json:"seq,omitempty"`
	Source *string `json:"source,omitempty"`
}

// PaneClosedSubscription is the "pane.closed" variant of Subscription.
type PaneClosedSubscription struct{}

func (PaneClosedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneClosedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneClosedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.closed", alias: alias(v)})
}

type PaneCopyMotion string

// PaneCopyMotion values.
const (
	PaneCopyMotionLineEnd              PaneCopyMotion = "line_end"
	PaneCopyMotionFirstNonBlank        PaneCopyMotion = "first_non_blank"
	PaneCopyMotionNextWordStart        PaneCopyMotion = "next_word_start"
	PaneCopyMotionPreviousWordStart    PaneCopyMotion = "previous_word_start"
	PaneCopyMotionNextWordEnd          PaneCopyMotion = "next_word_end"
	PaneCopyMotionNextBigWordStart     PaneCopyMotion = "next_big_word_start"
	PaneCopyMotionPreviousBigWordStart PaneCopyMotion = "previous_big_word_start"
	PaneCopyMotionNextBigWordEnd       PaneCopyMotion = "next_big_word_end"
	PaneCopyMotionPreviousParagraph    PaneCopyMotion = "previous_paragraph"
	PaneCopyMotionNextParagraph        PaneCopyMotion = "next_paragraph"
)

type PaneCopyMotionParams struct {
	ContentRevision *uint64        `json:"content_revision,omitempty"`
	Cursor          PaneTextPoint  `json:"cursor"`
	Motion          PaneCopyMotion `json:"motion"`
	PaneID          string         `json:"pane_id"`
}

type PaneCopySearchDirection string

// PaneCopySearchDirection values.
const (
	PaneCopySearchDirectionForward  PaneCopySearchDirection = "forward"
	PaneCopySearchDirectionBackward PaneCopySearchDirection = "backward"
)

type PaneCopySearchParams struct {
	ContentRevision uint64                  `json:"content_revision"`
	Cursor          PaneTextPoint           `json:"cursor"`
	Direction       PaneCopySearchDirection `json:"direction"`
	PaneID          string                  `json:"pane_id"`
	Previous        *PaneTextRange          `json:"previous,omitempty"`
	Query           string                  `json:"query"`
}

// PaneCreatedSubscription is the "pane.created" variant of Subscription.
type PaneCreatedSubscription struct{}

func (PaneCreatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneCreatedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneCreatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.created", alias: alias(v)})
}

type PaneCurrentParams struct {
	CallerPaneID *string `json:"caller_pane_id,omitempty"`
}

type PaneDirection string

// PaneDirection values.
const (
	PaneDirectionLeft  PaneDirection = "left"
	PaneDirectionRight PaneDirection = "right"
	PaneDirectionUp    PaneDirection = "up"
	PaneDirectionDown  PaneDirection = "down"
)

type PaneEdgesParams struct {
	PaneID *string `json:"pane_id,omitempty"`
}

type PaneEdgesResult struct {
	Down   bool               `json:"down"`
	Layout PaneLayoutSnapshot `json:"layout"`
	Left   bool               `json:"left"`
	PaneID string             `json:"pane_id"`
	Right  bool               `json:"right"`
	Up     bool               `json:"up"`
}

// PaneExitedSubscription is the "pane.exited" variant of Subscription.
type PaneExitedSubscription struct{}

func (PaneExitedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneExitedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneExitedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.exited", alias: alias(v)})
}

type PaneFocusDirectionParams struct {
	Direction PaneDirection `json:"direction"`
	PaneID    *string       `json:"pane_id,omitempty"`
}

type PaneFocusDirectionReason string

// PaneFocusDirectionReason values.
const (
	PaneFocusDirectionReasonNoNeighbor PaneFocusDirectionReason = "no_neighbor"
)

type PaneFocusDirectionResult struct {
	Changed       bool                      `json:"changed"`
	FocusedPaneID *string                   `json:"focused_pane_id,omitempty"`
	Layout        PaneLayoutSnapshot        `json:"layout"`
	Reason        *PaneFocusDirectionReason `json:"reason,omitempty"`
	SourcePaneID  string                    `json:"source_pane_id"`
}

// PaneFocusedSubscription is the "pane.focused" variant of Subscription.
type PaneFocusedSubscription struct{}

func (PaneFocusedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneFocusedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneFocusedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.focused", alias: alias(v)})
}

type PaneGraphicsClearParams struct {
	LayerID *string `json:"layer_id,omitempty"`
	PaneID  string  `json:"pane_id"`
}

type PaneGraphicsFormat string

// PaneGraphicsFormat values.
const (
	PaneGraphicsFormatPng  PaneGraphicsFormat = "png"
	PaneGraphicsFormatRgb  PaneGraphicsFormat = "rgb"
	PaneGraphicsFormatRgba PaneGraphicsFormat = "rgba"
	PaneGraphicsFormatBgra PaneGraphicsFormat = "bgra"
)

type PaneGraphicsPlacementParams struct {
	GridCols    *uint32 `json:"grid_cols,omitempty"`
	GridRows    *uint32 `json:"grid_rows,omitempty"`
	ViewportCol *int32  `json:"viewport_col,omitempty"`
	ViewportRow *int32  `json:"viewport_row,omitempty"`
}

type PaneGraphicsSetParams struct {
	DataBase64  string                       `json:"data_base64,omitempty"`
	Format      PaneGraphicsFormat           `json:"format"`
	ImageHeight uint32                       `json:"image_height"`
	ImageWidth  uint32                       `json:"image_width"`
	LayerID     *string                      `json:"layer_id,omitempty"`
	PaneID      string                       `json:"pane_id"`
	Placement   *PaneGraphicsPlacementParams `json:"placement,omitempty"`
	ZIndex      *int32                       `json:"z_index,omitempty"`
}

type PaneInfo struct {
	Agent                 *string           `json:"agent,omitempty"`
	AgentSession          *AgentSessionInfo `json:"agent_session,omitempty"`
	AgentStatus           AgentStatus       `json:"agent_status"`
	Cwd                   *string           `json:"cwd,omitempty"`
	DisplayAgent          *string           `json:"display_agent,omitempty"`
	Focused               bool              `json:"focused"`
	ForegroundCwd         *string           `json:"foreground_cwd,omitempty"`
	Label                 *string           `json:"label,omitempty"`
	PaneID                string            `json:"pane_id"`
	Revision              uint64            `json:"revision"`
	Scroll                *PaneScrollInfo   `json:"scroll,omitempty"`
	StateLabels           map[string]string `json:"state_labels,omitempty"`
	TabID                 string            `json:"tab_id"`
	TerminalID            string            `json:"terminal_id"`
	TerminalTitle         *string           `json:"terminal_title,omitempty"`
	TerminalTitleStripped *string           `json:"terminal_title_stripped,omitempty"`
	Title                 *string           `json:"title,omitempty"`
	Tokens                map[string]string `json:"tokens,omitempty"`
	WorkspaceID           string            `json:"workspace_id"`
}

type PaneInputSetParams struct {
	PaneID     string               `json:"pane_id"`
	RightClick PaneRightClickTarget `json:"right_click"`
}

type PaneLayoutPane struct {
	Focused bool           `json:"focused"`
	PaneID  string         `json:"pane_id"`
	Rect    PaneLayoutRect `json:"rect"`
}

type PaneLayoutParams struct {
	PaneID *string `json:"pane_id,omitempty"`
}

type PaneLayoutRect struct {
	Height uint16 `json:"height"`
	Width  uint16 `json:"width"`
	X      uint16 `json:"x"`
	Y      uint16 `json:"y"`
}

type PaneLayoutSnapshot struct {
	Area          PaneLayoutRect    `json:"area"`
	FocusedPaneID string            `json:"focused_pane_id"`
	Panes         []PaneLayoutPane  `json:"panes"`
	Splits        []PaneLayoutSplit `json:"splits"`
	TabID         string            `json:"tab_id"`
	WorkspaceID   string            `json:"workspace_id"`
	Zoomed        bool              `json:"zoomed"`
}

type PaneLayoutSplit struct {
	Direction SplitDirection `json:"direction"`
	ID        string         `json:"id"`
	Ratio     float64        `json:"ratio"`
	Rect      PaneLayoutRect `json:"rect"`
}

type PaneLinkActivateParams struct {
	Col              uint16  `json:"col"`
	ContentRevision  *uint64 `json:"content_revision,omitempty"`
	OffsetFromBottom *uint64 `json:"offset_from_bottom,omitempty"`
	PaneID           string  `json:"pane_id"`
	ViewportRow      uint16  `json:"viewport_row"`
}

type PaneListParams struct {
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

// PaneMoveDestination is a union of the types below, selected by the
// "type" field.
type PaneMoveDestination interface {
	isPaneMoveDestination()
}

func decodePaneMoveDestination(data []byte) (PaneMoveDestination, error) {
	var head struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Tag {
	case "tab":
		var value PaneMoveDestinationTab
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "new_tab":
		var value PaneMoveDestinationNewTab
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "new_workspace":
		var value PaneMoveDestinationNewWorkspace
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("herdr: unknown PaneMoveDestination %q", head.Tag)
}

// PaneMoveDestinationNewTab is the "new_tab" variant of
// PaneMoveDestination.
type PaneMoveDestinationNewTab struct {
	Label       *string `json:"label,omitempty"`
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

func (PaneMoveDestinationNewTab) isPaneMoveDestination() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneMoveDestinationNewTab) MarshalJSON() ([]byte, error) {
	type alias PaneMoveDestinationNewTab
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "new_tab", alias: alias(v)})
}

// PaneMoveDestinationNewWorkspace is the "new_workspace" variant of
// PaneMoveDestination.
type PaneMoveDestinationNewWorkspace struct {
	Label    *string `json:"label,omitempty"`
	TabLabel *string `json:"tab_label,omitempty"`
}

func (PaneMoveDestinationNewWorkspace) isPaneMoveDestination() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneMoveDestinationNewWorkspace) MarshalJSON() ([]byte, error) {
	type alias PaneMoveDestinationNewWorkspace
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "new_workspace", alias: alias(v)})
}

// PaneMoveDestinationTab is the "tab" variant of PaneMoveDestination.
type PaneMoveDestinationTab struct {
	Ratio        *float64       `json:"ratio,omitempty"`
	Split        SplitDirection `json:"split"`
	TabID        string         `json:"tab_id"`
	TargetPaneID *string        `json:"target_pane_id,omitempty"`
}

func (PaneMoveDestinationTab) isPaneMoveDestination() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneMoveDestinationTab) MarshalJSON() ([]byte, error) {
	type alias PaneMoveDestinationTab
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab", alias: alias(v)})
}

type PaneMoveParams struct {
	Destination PaneMoveDestination `json:"destination"`
	Focus       *bool               `json:"focus,omitempty"`
	PaneID      string              `json:"pane_id"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *PaneMoveParams) UnmarshalJSON(data []byte) error {
	type alias PaneMoveParams
	var aux struct {
		alias
		Destination json.RawMessage `json:"destination"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = PaneMoveParams(aux.alias)
	if len(aux.Destination) > 0 && string(aux.Destination) != "null" {
		decoded, err := decodePaneMoveDestination(aux.Destination)
		if err != nil {
			return err
		}
		v.Destination = decoded
	}
	return nil
}

type PaneMoveReason string

// PaneMoveReason values.
const (
	PaneMoveReasonSameTab   PaneMoveReason = "same_tab"
	PaneMoveReasonZoomedTab PaneMoveReason = "zoomed_tab"
)

type PaneMoveResult struct {
	Changed             bool                `json:"changed"`
	ClosedTabID         *string             `json:"closed_tab_id,omitempty"`
	ClosedWorkspaceID   *string             `json:"closed_workspace_id,omitempty"`
	CreatedTab          *TabInfo            `json:"created_tab,omitempty"`
	CreatedWorkspace    *WorkspaceInfo      `json:"created_workspace,omitempty"`
	FocusedPaneID       string              `json:"focused_pane_id"`
	Pane                PaneInfo            `json:"pane"`
	PreviousPaneID      string              `json:"previous_pane_id"`
	PreviousTabID       string              `json:"previous_tab_id"`
	PreviousWorkspaceID string              `json:"previous_workspace_id"`
	Reason              *PaneMoveReason     `json:"reason,omitempty"`
	SourceLayout        *PaneLayoutSnapshot `json:"source_layout,omitempty"`
	TargetLayout        PaneLayoutSnapshot  `json:"target_layout"`
}

// PaneMovedSubscription is the "pane.moved" variant of Subscription.
type PaneMovedSubscription struct{}

func (PaneMovedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneMovedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneMovedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.moved", alias: alias(v)})
}

type PaneNeighborParams struct {
	Direction PaneDirection `json:"direction"`
	PaneID    *string       `json:"pane_id,omitempty"`
}

type PaneNeighborResult struct {
	Direction      PaneDirection      `json:"direction"`
	Layout         PaneLayoutSnapshot `json:"layout"`
	NeighborPaneID *string            `json:"neighbor_pane_id,omitempty"`
	PaneID         string             `json:"pane_id"`
}

// PaneOutputMatchedSubscription is the "pane.output_matched" variant of
// Subscription.
type PaneOutputMatchedSubscription struct {
	Lines     *uint32     `json:"lines,omitempty"`
	Match     OutputMatch `json:"match"`
	PaneID    string      `json:"pane_id"`
	Source    ReadSource  `json:"source"`
	StripANSI *bool       `json:"strip_ansi,omitempty"`
}

func (PaneOutputMatchedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneOutputMatchedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneOutputMatchedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.output_matched", alias: alias(v)})
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *PaneOutputMatchedSubscription) UnmarshalJSON(data []byte) error {
	type alias PaneOutputMatchedSubscription
	var aux struct {
		alias
		Match json.RawMessage `json:"match"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = PaneOutputMatchedSubscription(aux.alias)
	if len(aux.Match) > 0 && string(aux.Match) != "null" {
		decoded, err := decodeOutputMatch(aux.Match)
		if err != nil {
			return err
		}
		v.Match = decoded
	}
	return nil
}

type PaneProcessInfo struct {
	ForegroundProcessGroupID *uint32                  `json:"foreground_process_group_id,omitempty"`
	ForegroundProcesses      []PaneProcessInfoProcess `json:"foreground_processes,omitempty"`
	PaneID                   string                   `json:"pane_id"`
	ShellPID                 *uint32                  `json:"shell_pid,omitempty"`
	TTY                      *string                  `json:"tty,omitempty"`
}

type PaneProcessInfoParams struct {
	PaneID *string `json:"pane_id,omitempty"`
}

type PaneProcessInfoProcess struct {
	Argv    []string `json:"argv,omitempty"`
	Argv0   *string  `json:"argv0,omitempty"`
	Cmdline *string  `json:"cmdline,omitempty"`
	Cwd     *string  `json:"cwd,omitempty"`
	Name    string   `json:"name"`
	PID     uint32   `json:"pid"`
}

type PaneReadParams struct {
	Format    ReadFormat `json:"format,omitempty"`
	Lines     *uint32    `json:"lines,omitempty"`
	PaneID    string     `json:"pane_id"`
	Source    ReadSource `json:"source"`
	StripANSI *bool      `json:"strip_ansi,omitempty"`
}

type PaneReadResult struct {
	Format      ReadFormat `json:"format"`
	PaneID      string     `json:"pane_id"`
	Revision    uint64     `json:"revision"`
	Source      ReadSource `json:"source"`
	TabID       string     `json:"tab_id"`
	Text        string     `json:"text"`
	Truncated   bool       `json:"truncated"`
	WorkspaceID string     `json:"workspace_id"`
}

type PaneReleaseAgentParams struct {
	Agent  string  `json:"agent"`
	PaneID string  `json:"pane_id"`
	Seq    *uint64 `json:"seq,omitempty"`
	Source string  `json:"source"`
}

type PaneRenameParams struct {
	Label  *string `json:"label,omitempty"`
	PaneID string  `json:"pane_id"`
}

type PaneReportAgentParams struct {
	Agent            string         `json:"agent"`
	AgentSessionID   *string        `json:"agent_session_id,omitempty"`
	AgentSessionPath *string        `json:"agent_session_path,omitempty"`
	Message          *string        `json:"message,omitempty"`
	PaneID           string         `json:"pane_id"`
	Seq              *uint64        `json:"seq,omitempty"`
	Source           string         `json:"source"`
	State            PaneAgentState `json:"state"`
}

type PaneReportAgentSessionParams struct {
	Agent              string  `json:"agent"`
	AgentSessionID     *string `json:"agent_session_id,omitempty"`
	AgentSessionPath   *string `json:"agent_session_path,omitempty"`
	PaneID             string  `json:"pane_id"`
	Seq                *uint64 `json:"seq,omitempty"`
	SessionStartSource *string `json:"session_start_source,omitempty"`
	Source             string  `json:"source"`
}

type PaneReportMetadataParams struct {
	Agent             *string            `json:"agent,omitempty"`
	AppliesToSource   *string            `json:"applies_to_source,omitempty"`
	ClearDisplayAgent *bool              `json:"clear_display_agent,omitempty"`
	ClearStateLabels  *bool              `json:"clear_state_labels,omitempty"`
	ClearTitle        *bool              `json:"clear_title,omitempty"`
	DisplayAgent      *string            `json:"display_agent,omitempty"`
	PaneID            string             `json:"pane_id"`
	Seq               *uint64            `json:"seq,omitempty"`
	Source            string             `json:"source"`
	StateLabels       map[string]string  `json:"state_labels,omitempty"`
	Title             *string            `json:"title,omitempty"`
	Tokens            map[string]*string `json:"tokens,omitempty"`
	TTLMs             *uint64            `json:"ttl_ms,omitempty"`
}

type PaneResizeParams struct {
	Amount    *float64      `json:"amount,omitempty"`
	Direction PaneDirection `json:"direction"`
	PaneID    *string       `json:"pane_id,omitempty"`
}

type PaneResizeReason string

// PaneResizeReason values.
const (
	PaneResizeReasonUnchanged PaneResizeReason = "unchanged"
)

type PaneResizeResult struct {
	Changed       bool               `json:"changed"`
	FocusedPaneID string             `json:"focused_pane_id"`
	Layout        PaneLayoutSnapshot `json:"layout"`
	PaneID        string             `json:"pane_id"`
	Reason        *PaneResizeReason  `json:"reason,omitempty"`
}

type PaneRightClickTarget string

// PaneRightClickTarget values.
const (
	PaneRightClickTargetHerdr PaneRightClickTarget = "herdr"
	PaneRightClickTargetPane  PaneRightClickTarget = "pane"
)

// PaneScrollChangedSubscription is the "pane.scroll_changed" variant of
// Subscription.
type PaneScrollChangedSubscription struct {
	PaneID string `json:"pane_id"`
}

func (PaneScrollChangedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneScrollChangedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneScrollChangedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.scroll_changed", alias: alias(v)})
}

type PaneScrollInfo struct {
	MaxOffsetFromBottom uint64 `json:"max_offset_from_bottom"`
	OffsetFromBottom    uint64 `json:"offset_from_bottom"`
	ViewportRows        uint64 `json:"viewport_rows"`
}

type PaneScrollParams struct {
	OffsetFromBottom uint64 `json:"offset_from_bottom"`
	PaneID           string `json:"pane_id"`
}

type PaneSelectionReadParams struct {
	Anchor          PaneTextPoint `json:"anchor"`
	ContentRevision *uint64       `json:"content_revision,omitempty"`
	Cursor          PaneTextPoint `json:"cursor"`
	PaneID          string        `json:"pane_id"`
}

type PaneSendInputParams struct {
	Keys   []string `json:"keys,omitempty"`
	PaneID string   `json:"pane_id"`
	Text   string   `json:"text,omitempty"`
}

type PaneSendKeysParams struct {
	Keys   []string `json:"keys"`
	PaneID string   `json:"pane_id"`
}

type PaneSendTextParams struct {
	PaneID string `json:"pane_id"`
	Text   string `json:"text"`
}

type PaneSplitParams struct {
	Cwd          *string              `json:"cwd,omitempty"`
	Direction    SplitDirection       `json:"direction"`
	Env          map[string]string    `json:"env,omitempty"`
	Focus        *bool                `json:"focus,omitempty"`
	Ratio        *float64             `json:"ratio,omitempty"`
	RightClick   PaneRightClickTarget `json:"right_click,omitempty"`
	TargetPaneID *string              `json:"target_pane_id,omitempty"`
	WorkspaceID  *string              `json:"workspace_id,omitempty"`
}

type PaneSwapParams struct {
	Direction    *PaneDirection `json:"direction,omitempty"`
	PaneID       *string        `json:"pane_id,omitempty"`
	SourcePaneID *string        `json:"source_pane_id,omitempty"`
	TargetPaneID *string        `json:"target_pane_id,omitempty"`
}

type PaneSwapReason string

// PaneSwapReason values.
const (
	PaneSwapReasonNoNeighbor PaneSwapReason = "no_neighbor"
	PaneSwapReasonSamePane   PaneSwapReason = "same_pane"
	PaneSwapReasonNotFound   PaneSwapReason = "not_found"
	PaneSwapReasonCrossTab   PaneSwapReason = "cross_tab"
)

type PaneSwapResult struct {
	Changed       bool               `json:"changed"`
	FocusedPaneID string             `json:"focused_pane_id"`
	Layout        PaneLayoutSnapshot `json:"layout"`
	Reason        *PaneSwapReason    `json:"reason,omitempty"`
	SourcePaneID  string             `json:"source_pane_id"`
	TargetPaneID  *string            `json:"target_pane_id,omitempty"`
}

type PaneTarget struct {
	PaneID string `json:"pane_id"`
}

type PaneTextPoint struct {
	Col uint16 `json:"col"`
	Row uint32 `json:"row"`
}

type PaneTextRange struct {
	End   PaneTextPoint `json:"end"`
	Start PaneTextPoint `json:"start"`
}

// PaneUpdatedSubscription is the "pane.updated" variant of Subscription.
type PaneUpdatedSubscription struct{}

func (PaneUpdatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v PaneUpdatedSubscription) MarshalJSON() ([]byte, error) {
	type alias PaneUpdatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "pane.updated", alias: alias(v)})
}

type PaneWaitForOutputParams struct {
	Lines     *uint32     `json:"lines,omitempty"`
	Match     OutputMatch `json:"match"`
	PaneID    string      `json:"pane_id"`
	Source    ReadSource  `json:"source"`
	StripANSI *bool       `json:"strip_ansi,omitempty"`
	TimeoutMs *uint64     `json:"timeout_ms,omitempty"`
}

// UnmarshalJSON decodes the fields that hold a union value.
func (v *PaneWaitForOutputParams) UnmarshalJSON(data []byte) error {
	type alias PaneWaitForOutputParams
	var aux struct {
		alias
		Match json.RawMessage `json:"match"`
	}
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	*v = PaneWaitForOutputParams(aux.alias)
	if len(aux.Match) > 0 && string(aux.Match) != "null" {
		decoded, err := decodeOutputMatch(aux.Match)
		if err != nil {
			return err
		}
		v.Match = decoded
	}
	return nil
}

type PaneZoomMode string

// PaneZoomMode values.
const (
	PaneZoomModeToggle PaneZoomMode = "toggle"
	PaneZoomModeOn     PaneZoomMode = "on"
	PaneZoomModeOff    PaneZoomMode = "off"
)

type PaneZoomParams struct {
	Mode   PaneZoomMode `json:"mode,omitempty"`
	PaneID *string      `json:"pane_id,omitempty"`
}

type PaneZoomReason string

// PaneZoomReason values.
const (
	PaneZoomReasonSinglePane      PaneZoomReason = "single_pane"
	PaneZoomReasonAlreadyZoomed   PaneZoomReason = "already_zoomed"
	PaneZoomReasonAlreadyUnzoomed PaneZoomReason = "already_unzoomed"
)

type PaneZoomResult struct {
	Changed       bool               `json:"changed"`
	FocusChanged  bool               `json:"focus_changed"`
	FocusedPaneID string             `json:"focused_pane_id"`
	Layout        PaneLayoutSnapshot `json:"layout"`
	PaneID        string             `json:"pane_id"`
	Reason        *PaneZoomReason    `json:"reason,omitempty"`
	ZoomChanged   bool               `json:"zoom_changed"`
	Zoomed        bool               `json:"zoomed"`
}

type PingParams struct{}

type PluginActionContext string

// PluginActionContext values.
const (
	PluginActionContextGlobal    PluginActionContext = "global"
	PluginActionContextWorkspace PluginActionContext = "workspace"
	PluginActionContextTab       PluginActionContext = "tab"
	PluginActionContextPane      PluginActionContext = "pane"
	PluginActionContextSelection PluginActionContext = "selection"
)

type PluginActionInfo struct {
	ActionID    string                `json:"action_id"`
	Command     []string              `json:"command"`
	Contexts    []PluginActionContext `json:"contexts,omitempty"`
	Description *string               `json:"description,omitempty"`
	Platforms   []PluginPlatform      `json:"platforms,omitempty"`
	PluginID    string                `json:"plugin_id"`
	Title       string                `json:"title"`
}

type PluginActionInvokeParams struct {
	ActionID string                   `json:"action_id"`
	Context  *PluginInvocationContext `json:"context,omitempty"`
	PluginID *string                  `json:"plugin_id,omitempty"`
}

type PluginActionListParams struct {
	PluginID *string `json:"plugin_id,omitempty"`
}

type PluginCommandLogInfo struct {
	ActionID       *string             `json:"action_id,omitempty"`
	Command        []string            `json:"command"`
	Error          *string             `json:"error,omitempty"`
	Event          *string             `json:"event,omitempty"`
	ExitCode       *int32              `json:"exit_code,omitempty"`
	FinishedUnixMs *uint64             `json:"finished_unix_ms,omitempty"`
	LogID          string              `json:"log_id"`
	PluginID       string              `json:"plugin_id"`
	StartedUnixMs  uint64              `json:"started_unix_ms"`
	Status         PluginCommandStatus `json:"status"`
	Stderr         *string             `json:"stderr,omitempty"`
	Stdout         *string             `json:"stdout,omitempty"`
}

type PluginCommandStatus string

// PluginCommandStatus values.
const (
	PluginCommandStatusRunning   PluginCommandStatus = "running"
	PluginCommandStatusSucceeded PluginCommandStatus = "succeeded"
	PluginCommandStatusFailed    PluginCommandStatus = "failed"
)

type PluginInvocationContext struct {
	ClickedURL        *string                `json:"clicked_url,omitempty"`
	CorrelationID     *string                `json:"correlation_id,omitempty"`
	FocusedPaneAgent  *string                `json:"focused_pane_agent,omitempty"`
	FocusedPaneCwd    *string                `json:"focused_pane_cwd,omitempty"`
	FocusedPaneID     *string                `json:"focused_pane_id,omitempty"`
	FocusedPaneStatus *AgentStatus           `json:"focused_pane_status,omitempty"`
	InvocationSource  *string                `json:"invocation_source,omitempty"`
	LinkHandlerID     *string                `json:"link_handler_id,omitempty"`
	SelectedText      *string                `json:"selected_text,omitempty"`
	TabID             *string                `json:"tab_id,omitempty"`
	TabLabel          *string                `json:"tab_label,omitempty"`
	WorkspaceCwd      *string                `json:"workspace_cwd,omitempty"`
	WorkspaceID       *string                `json:"workspace_id,omitempty"`
	WorkspaceLabel    *string                `json:"workspace_label,omitempty"`
	Worktree          *WorkspaceWorktreeInfo `json:"worktree,omitempty"`
}

type PluginLinkParams struct {
	Enabled *bool             `json:"enabled,omitempty"`
	Path    string            `json:"path"`
	Source  *PluginSourceInfo `json:"source,omitempty"`
}

type PluginListParams struct {
	PluginID *string `json:"plugin_id,omitempty"`
}

type PluginLogListParams struct {
	Limit    *uint64 `json:"limit,omitempty"`
	PluginID *string `json:"plugin_id,omitempty"`
}

type PluginManifestAction struct {
	Command     []string              `json:"command"`
	Contexts    []PluginActionContext `json:"contexts,omitempty"`
	Description *string               `json:"description,omitempty"`
	ID          string                `json:"id"`
	Platforms   []PluginPlatform      `json:"platforms,omitempty"`
	Title       string                `json:"title"`
}

type PluginManifestBuild struct {
	Command   []string         `json:"command"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
}

type PluginManifestEventHook struct {
	Command   []string         `json:"command"`
	On        string           `json:"on"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
}

type PluginManifestLinkHandler struct {
	Action    string           `json:"action"`
	ID        string           `json:"id"`
	Pattern   string           `json:"pattern"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
	Title     string           `json:"title"`
}

type PluginManifestPane struct {
	Command     []string            `json:"command"`
	Description *string             `json:"description,omitempty"`
	Height      *PopupSize          `json:"height,omitempty"`
	ID          string              `json:"id"`
	Placement   PluginPanePlacement `json:"placement,omitempty"`
	Platforms   []PluginPlatform    `json:"platforms,omitempty"`
	Title       string              `json:"title"`
	Width       *PopupSize          `json:"width,omitempty"`
}

type PluginManifestStartup struct {
	Command   []string         `json:"command"`
	Platforms []PluginPlatform `json:"platforms,omitempty"`
}

type PluginPaneCloseParams struct {
	PaneID string `json:"pane_id"`
}

type PluginPaneFocusParams struct {
	PaneID string `json:"pane_id"`
}

type PluginPaneInfo struct {
	Entrypoint string   `json:"entrypoint"`
	Pane       PaneInfo `json:"pane"`
	PluginID   string   `json:"plugin_id"`
}

type PluginPaneOpenParams struct {
	Cwd          *string              `json:"cwd,omitempty"`
	Direction    *SplitDirection      `json:"direction,omitempty"`
	Entrypoint   string               `json:"entrypoint"`
	Env          map[string]string    `json:"env,omitempty"`
	Focus        *bool                `json:"focus,omitempty"`
	Height       *PopupSize           `json:"height,omitempty"`
	Placement    *PluginPanePlacement `json:"placement,omitempty"`
	PluginID     string               `json:"plugin_id"`
	TargetPaneID *string              `json:"target_pane_id,omitempty"`
	Width        *PopupSize           `json:"width,omitempty"`
	WorkspaceID  *string              `json:"workspace_id,omitempty"`
}

type PluginPanePlacement string

// PluginPanePlacement values.
const (
	PluginPanePlacementOverlay PluginPanePlacement = "overlay"
	PluginPanePlacementPopup   PluginPanePlacement = "popup"
	PluginPanePlacementSplit   PluginPanePlacement = "split"
	PluginPanePlacementTab     PluginPanePlacement = "tab"
	PluginPanePlacementZoomed  PluginPanePlacement = "zoomed"
)

type PluginPlatform string

// PluginPlatform values.
const (
	PluginPlatformLinux   PluginPlatform = "linux"
	PluginPlatformMacos   PluginPlatform = "macos"
	PluginPlatformWindows PluginPlatform = "windows"
)

type PluginSetEnabledParams struct {
	PluginID string `json:"plugin_id"`
}

type PluginSourceInfo struct {
	InstalledUnixMs *uint64          `json:"installed_unix_ms,omitempty"`
	Kind            PluginSourceKind `json:"kind,omitempty"`
	ManagedPath     *string          `json:"managed_path,omitempty"`
	Owner           *string          `json:"owner,omitempty"`
	Repo            *string          `json:"repo,omitempty"`
	RequestedRef    *string          `json:"requested_ref,omitempty"`
	ResolvedCommit  *string          `json:"resolved_commit,omitempty"`
	Subdir          *string          `json:"subdir,omitempty"`
}

type PluginSourceKind string

// PluginSourceKind values.
const (
	PluginSourceKindLocal  PluginSourceKind = "local"
	PluginSourceKindGithub PluginSourceKind = "github"
)

type PluginUnlinkParams struct {
	PluginID string `json:"plugin_id"`
}

type ProductAnnouncementDismissParams struct {
	ID      string `json:"id"`
	Version string `json:"version"`
}

type ReadFormat string

// ReadFormat values.
const (
	ReadFormatText ReadFormat = "text"
	ReadFormatANSI ReadFormat = "ansi"
)

type ReadSource string

// ReadSource values.
const (
	ReadSourceVisible         ReadSource = "visible"
	ReadSourceRecent          ReadSource = "recent"
	ReadSourceRecentUnwrapped ReadSource = "recent_unwrapped"
	ReadSourceDetection       ReadSource = "detection"
)

type ReleaseNotesDismissParams struct {
	Version string `json:"version"`
}

type ServerCapabilities struct {
	DetachedServerDaemon *bool `json:"detached_server_daemon,omitempty"`

	// Stable client-owned endpoint generation supported by this server.
	EndpointProtocolGeneration *uint32 `json:"endpoint_protocol_generation,omitempty"`

	// Whether this server supports endpoint health probes.
	HealthCheck *bool `json:"health_check,omitempty"`
	LiveHandoff bool  `json:"live_handoff"`

	// Whether this server supports explicit client-shell surface interest.
	SurfaceInterest *bool `json:"surface_interest,omitempty"`
}

type ServerLiveHandoffParams struct {
	ExpectedProtocol *uint32 `json:"expected_protocol,omitempty"`
	ExpectedVersion  *string `json:"expected_version,omitempty"`
	ImportExe        *string `json:"import_exe,omitempty"`
}

type SessionSnapshot struct {
	Agents             []AgentInfo          `json:"agents"`
	FocusedPaneID      *string              `json:"focused_pane_id,omitempty"`
	FocusedTabID       *string              `json:"focused_tab_id,omitempty"`
	FocusedWorkspaceID *string              `json:"focused_workspace_id,omitempty"`
	Layouts            []PaneLayoutSnapshot `json:"layouts"`
	Panes              []PaneInfo           `json:"panes"`
	Protocol           uint32               `json:"protocol"`
	Tabs               []TabInfo            `json:"tabs"`
	Version            string               `json:"version"`
	Workspaces         []WorkspaceInfo      `json:"workspaces"`
}

type SplitDirection string

// SplitDirection values.
const (
	SplitDirectionRight SplitDirection = "right"
	SplitDirectionDown  SplitDirection = "down"
)

// Subscription is a union of the types below, selected by the "type"
// field.
type Subscription interface {
	isSubscription()
}

func decodeSubscription(data []byte) (Subscription, error) {
	var head struct {
		Tag string `json:"type"`
	}
	if err := json.Unmarshal(data, &head); err != nil {
		return nil, err
	}
	switch head.Tag {
	case "workspace.created":
		var value WorkspaceCreatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.updated":
		var value WorkspaceUpdatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.metadata_updated":
		var value WorkspaceMetadataUpdatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.renamed":
		var value WorkspaceRenamedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.moved":
		var value WorkspaceMovedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.reordered":
		var value WorkspaceReorderedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.closed":
		var value WorkspaceClosedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "workspace.focused":
		var value WorkspaceFocusedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "worktree.created":
		var value WorktreeCreatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "worktree.opened":
		var value WorktreeOpenedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "worktree.removed":
		var value WorktreeRemovedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab.created":
		var value TabCreatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab.closed":
		var value TabClosedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab.focused":
		var value TabFocusedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab.renamed":
		var value TabRenamedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "tab.moved":
		var value TabMovedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.created":
		var value PaneCreatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.closed":
		var value PaneClosedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.updated":
		var value PaneUpdatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.focused":
		var value PaneFocusedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.moved":
		var value PaneMovedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.exited":
		var value PaneExitedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.agent_detected":
		var value PaneAgentDetectedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.output_matched":
		var value PaneOutputMatchedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.agent_status_changed":
		var value PaneAgentStatusChangedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "pane.scroll_changed":
		var value PaneScrollChangedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	case "layout.updated":
		var value LayoutUpdatedSubscription
		if err := json.Unmarshal(data, &value); err != nil {
			return nil, err
		}
		return &value, nil
	}
	return nil, fmt.Errorf("herdr: unknown Subscription %q", head.Tag)
}

// TabClosedSubscription is the "tab.closed" variant of Subscription.
type TabClosedSubscription struct{}

func (TabClosedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v TabClosedSubscription) MarshalJSON() ([]byte, error) {
	type alias TabClosedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab.closed", alias: alias(v)})
}

type TabCreateParams struct {
	Cwd         *string           `json:"cwd,omitempty"`
	Env         map[string]string `json:"env,omitempty"`
	Focus       *bool             `json:"focus,omitempty"`
	Label       *string           `json:"label,omitempty"`
	WorkspaceID *string           `json:"workspace_id,omitempty"`
}

// TabCreatedSubscription is the "tab.created" variant of Subscription.
type TabCreatedSubscription struct{}

func (TabCreatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v TabCreatedSubscription) MarshalJSON() ([]byte, error) {
	type alias TabCreatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab.created", alias: alias(v)})
}

// TabFocusedSubscription is the "tab.focused" variant of Subscription.
type TabFocusedSubscription struct{}

func (TabFocusedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v TabFocusedSubscription) MarshalJSON() ([]byte, error) {
	type alias TabFocusedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab.focused", alias: alias(v)})
}

type TabInfo struct {
	AgentStatus AgentStatus `json:"agent_status"`
	Focused     bool        `json:"focused"`
	Label       string      `json:"label"`
	Number      uint64      `json:"number"`
	PaneCount   uint64      `json:"pane_count"`
	TabID       string      `json:"tab_id"`
	WorkspaceID string      `json:"workspace_id"`
}

type TabListParams struct {
	WorkspaceID *string `json:"workspace_id,omitempty"`
}

type TabMoveParams struct {
	InsertIndex uint64 `json:"insert_index"`
	TabID       string `json:"tab_id"`
}

// TabMovedSubscription is the "tab.moved" variant of Subscription.
type TabMovedSubscription struct{}

func (TabMovedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v TabMovedSubscription) MarshalJSON() ([]byte, error) {
	type alias TabMovedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab.moved", alias: alias(v)})
}

type TabRenameParams struct {
	Label string `json:"label"`
	TabID string `json:"tab_id"`
}

// TabRenamedSubscription is the "tab.renamed" variant of Subscription.
type TabRenamedSubscription struct{}

func (TabRenamedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v TabRenamedSubscription) MarshalJSON() ([]byte, error) {
	type alias TabRenamedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "tab.renamed", alias: alias(v)})
}

type TabTarget struct {
	TabID string `json:"tab_id"`
}

type ToastHerdrPosition string

// ToastHerdrPosition values.
const (
	ToastHerdrPositionTopLeft     ToastHerdrPosition = "top-left"
	ToastHerdrPositionTopRight    ToastHerdrPosition = "top-right"
	ToastHerdrPositionBottomLeft  ToastHerdrPosition = "bottom-left"
	ToastHerdrPositionBottomRight ToastHerdrPosition = "bottom-right"
)

type WorkspaceCloseParams struct {
	CloseGroup  *bool  `json:"close_group,omitempty"`
	WorkspaceID string `json:"workspace_id"`
}

// WorkspaceClosedSubscription is the "workspace.closed" variant of
// Subscription.
type WorkspaceClosedSubscription struct{}

func (WorkspaceClosedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceClosedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceClosedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.closed", alias: alias(v)})
}

type WorkspaceCreateParams struct {
	Cwd   *string           `json:"cwd,omitempty"`
	Env   map[string]string `json:"env,omitempty"`
	Focus *bool             `json:"focus,omitempty"`
	Label *string           `json:"label,omitempty"`

	// Workspace whose focused pane supplies the `follow` cwd policy.
	SourceWorkspaceID *string `json:"source_workspace_id,omitempty"`
}

// WorkspaceCreatedSubscription is the "workspace.created" variant of
// Subscription.
type WorkspaceCreatedSubscription struct{}

func (WorkspaceCreatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceCreatedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceCreatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.created", alias: alias(v)})
}

// WorkspaceFocusedSubscription is the "workspace.focused" variant of
// Subscription.
type WorkspaceFocusedSubscription struct{}

func (WorkspaceFocusedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceFocusedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceFocusedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.focused", alias: alias(v)})
}

type WorkspaceInfo struct {
	ActiveTabID string                 `json:"active_tab_id"`
	AgentStatus AgentStatus            `json:"agent_status"`
	Focused     bool                   `json:"focused"`
	Label       string                 `json:"label"`
	Number      uint64                 `json:"number"`
	PaneCount   uint64                 `json:"pane_count"`
	TabCount    uint64                 `json:"tab_count"`
	Tokens      map[string]string      `json:"tokens,omitempty"`
	WorkspaceID string                 `json:"workspace_id"`
	Worktree    *WorkspaceWorktreeInfo `json:"worktree,omitempty"`
}

// WorkspaceMetadataUpdatedSubscription is the "workspace.metadata_updated"
// variant of Subscription.
type WorkspaceMetadataUpdatedSubscription struct{}

func (WorkspaceMetadataUpdatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceMetadataUpdatedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceMetadataUpdatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.metadata_updated", alias: alias(v)})
}

type WorkspaceMoveBlockParams struct {
	BeforeWorkspaceID *string  `json:"before_workspace_id,omitempty"`
	WorkspaceIds      []string `json:"workspace_ids"`
}

type WorkspaceMoveParams struct {
	InsertIndex uint64 `json:"insert_index"`
	WorkspaceID string `json:"workspace_id"`
}

// WorkspaceMovedSubscription is the "workspace.moved" variant of
// Subscription.
type WorkspaceMovedSubscription struct{}

func (WorkspaceMovedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceMovedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceMovedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.moved", alias: alias(v)})
}

type WorkspaceRenameParams struct {
	Label       string `json:"label"`
	WorkspaceID string `json:"workspace_id"`
}

// WorkspaceRenamedSubscription is the "workspace.renamed" variant of
// Subscription.
type WorkspaceRenamedSubscription struct{}

func (WorkspaceRenamedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceRenamedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceRenamedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.renamed", alias: alias(v)})
}

// WorkspaceReorderedSubscription is the "workspace.reordered" variant of
// Subscription.
type WorkspaceReorderedSubscription struct{}

func (WorkspaceReorderedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceReorderedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceReorderedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.reordered", alias: alias(v)})
}

type WorkspaceReportMetadataParams struct {
	Seq         *uint64            `json:"seq,omitempty"`
	Source      string             `json:"source"`
	Tokens      map[string]*string `json:"tokens"`
	TTLMs       *uint64            `json:"ttl_ms,omitempty"`
	WorkspaceID string             `json:"workspace_id"`
}

type WorkspaceTarget struct {
	WorkspaceID string `json:"workspace_id"`
}

// WorkspaceUpdatedSubscription is the "workspace.updated" variant of
// Subscription.
type WorkspaceUpdatedSubscription struct{}

func (WorkspaceUpdatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorkspaceUpdatedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorkspaceUpdatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "workspace.updated", alias: alias(v)})
}

type WorkspaceWorktreeInfo struct {
	CheckoutPath     string `json:"checkout_path"`
	IsLinkedWorktree bool   `json:"is_linked_worktree"`
	RepoKey          string `json:"repo_key"`
	RepoName         string `json:"repo_name"`
	RepoRoot         string `json:"repo_root"`
}

type WorktreeCreateParams struct {
	Base            *string `json:"base,omitempty"`
	Branch          *string `json:"branch,omitempty"`
	Cwd             *string `json:"cwd,omitempty"`
	Focus           *bool   `json:"focus,omitempty"`
	Label           *string `json:"label,omitempty"`
	Path            *string `json:"path,omitempty"`
	TrustRepository *bool   `json:"trust_repository,omitempty"`
	WorkspaceID     *string `json:"workspace_id,omitempty"`
}

// WorktreeCreatedSubscription is the "worktree.created" variant of
// Subscription.
type WorktreeCreatedSubscription struct{}

func (WorktreeCreatedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorktreeCreatedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorktreeCreatedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "worktree.created", alias: alias(v)})
}

type WorktreeInfo struct {
	Branch           *string `json:"branch,omitempty"`
	IsBare           bool    `json:"is_bare"`
	IsDetached       bool    `json:"is_detached"`
	IsLinkedWorktree bool    `json:"is_linked_worktree"`
	IsPrunable       bool    `json:"is_prunable"`
	Label            string  `json:"label"`
	OpenWorkspaceID  *string `json:"open_workspace_id,omitempty"`
	Path             string  `json:"path"`
}

type WorktreeListParams struct {
	Cwd             *string `json:"cwd,omitempty"`
	TrustRepository *bool   `json:"trust_repository,omitempty"`
	WorkspaceID     *string `json:"workspace_id,omitempty"`
}

type WorktreeOpenParams struct {
	Branch          *string `json:"branch,omitempty"`
	Cwd             *string `json:"cwd,omitempty"`
	Focus           *bool   `json:"focus,omitempty"`
	Label           *string `json:"label,omitempty"`
	Path            *string `json:"path,omitempty"`
	TrustRepository *bool   `json:"trust_repository,omitempty"`
	WorkspaceID     *string `json:"workspace_id,omitempty"`
}

// WorktreeOpenedSubscription is the "worktree.opened" variant of
// Subscription.
type WorktreeOpenedSubscription struct{}

func (WorktreeOpenedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorktreeOpenedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorktreeOpenedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "worktree.opened", alias: alias(v)})
}

type WorktreeRemoveParams struct {
	Force           *bool  `json:"force,omitempty"`
	TrustRepository *bool  `json:"trust_repository,omitempty"`
	WorkspaceID     string `json:"workspace_id"`
}

// WorktreeRemovedSubscription is the "worktree.removed" variant of
// Subscription.
type WorktreeRemovedSubscription struct{}

func (WorktreeRemovedSubscription) isSubscription() {}

// MarshalJSON writes the object with its "type" field.
func (v WorktreeRemovedSubscription) MarshalJSON() ([]byte, error) {
	type alias WorktreeRemovedSubscription
	return json.Marshal(struct {
		Type string `json:"type"`
		alias
	}{Type: "worktree.removed", alias: alias(v)})
}

type WorktreeSourceInfo struct {
	RepoKey            string  `json:"repo_key"`
	RepoName           string  `json:"repo_name"`
	RepoRoot           string  `json:"repo_root"`
	SourceCheckoutPath string  `json:"source_checkout_path"`
	SourceWorkspaceID  *string `json:"source_workspace_id,omitempty"`
}
